import json

t = {
    # 000-050
    1232: "Ayase: Even though it's such a gorgeous building,",
    1233: "Brown: Whether it's ghosts or whatever,",
    1234: "Elly: A mansion where a ghost appears... That sounds rather fascinating.",
    1235: "Reiji: How long do you guys plan on dawdling around?",
    1236: "Let's go.",
    1237: "Leave it alone.",
    1238: "Receptionist: Huh?",
    1239: "What business do you have?",
    1240: "Could you possibly be from over there?",
    1241: "It's broken and won't open.",
    1242: "Maki: Secrets that even the company employees don't know...",
    1243: "Just what kind of company is this?",
    1244: "Mark: He's grinning like a smug bastard up on the top floor!",
    1245: "Nanjo: They say fools and smoke love high places.",
    1246: "Brown: Even the people in the company don't know what's going on, huh?",
    1247: "Just kidding~",
    1248: "That's crazy! Hearing the names of demons walking outside...",
    1249: "SEBEC Employee: High schoolers like you guys are here?!",
    1250: "Must be tough on you kids too.",
    1251: "SEBEC Employee: Who on earth do you think you are?!",
    1252: "Maki: These people too,",
    1253: "Ayase: Our school's students came here?",
    1254: "Elly: Other students from our school came here besides us?",
    1255: "Maki: We have to restore the town to how it was!",
    1256: "Mark: Let's hurry up and find Kandori!",
    1257: "Nanjo: In a place like this,",
    1258: "Nanjo: In a place like this,",
    1259: "Ayase: Let's go beat the snot outta Kandori!",
    1260: "Hey, hurry up~!!",
    1261: "Brown: As long as we're around,",
    1262: "we won't let you do whatever you please!",
    1263: "Reiji: I'll finish this.",
    1264: "Yukino: Stand back, everyone.",
    1265: "Let's move out.",
    1266: "Keep your guard up.",
    1267: "SEBEC Employee: What are high schoolers doing here?!",
    1268: "This is no place for kids!",
    1269: "Get out before the guards find you!",
    1270: "Maki: We came to stop Kandori!",
    1271: "Where is he?!",
    1272: "SEBEC Employee: President Kandori?",
    1273: "He's on the executive floor at the top,",
    1274: "but you'll never make it past the security doors.",
    1275: "Mark: We'll see about that!",
    1276: "Nanjo: We possess the means to bypass your security.",
    1277: "Step aside.",
    1278: "Elly: Please do not get in our way.",
    1279: "Brown: Yeah, out of the way, small fry!",
    1280: "Ayase: We're in a hurry, so move it~!",
    1281: "Reiji: Out of my sight.",

    # 051-100
    1282: "The elevator is out of order.",
    1283: "We'll have to take the stairs.",
    1284: "Watch out for security cameras and laser traps.",
    1285: "SEBEC's defenses are tight.",
    1286: "Scientist: The Deva System is functioning perfectly!",
    1287: "Dimensional resonance is stabilizing!",
    1288: "Maki: What are you doing with that machine?!",
    1289: "Scientist: Reshaping reality according to human thought!",
    1290: "Isn't it magnificent?!",
    1291: "Nanjo: Utter madness.",
    1292: "Tampering with the laws of existence will only bring ruin.",
    1293: "Mark: Cut the power to that thing!",
    1294: "Scientist: You can't stop it now! It's already begun!",
    1295: "Security Guard: Intruders detected in Sector 4!",
    1296: "All units, eliminate the targets!",
    1297: "Reiji: Bring it on, tin cans!",
    1298: "Persona!",
    1299: "Wipe them out!",
    1300: "All clear.",
    1301: "Let's keep climbing.",
    1302: "The higher we go, the stronger the demonic presence.",
    1303: "Stay focused.",
    1304: "Check the office terminals for keycards.",
    1305: "Found the Red Keycard!",
    1306: "Now we can unlock the 4th-floor laboratory.",
    1307: "Proceed with caution.",
    1308: "What's behind this door?",
    1309: "A research room.",
    1310: "Look at these documents...",
    1311: "SEBEC's covert experiments on human cognition.",
    1312: "They were experimenting on St. Hermelin students!",
    1313: "Unforgivable!",
    1314: "Kandori will pay dearly for this.",
    1315: "Let's find the master control room.",
    1316: "Next floor.",
    1317: "Security Guard: Stop right there!",
    1318: "Open fire!",
    1319: "Take cover!",
    1320: "Return fire with Personas!",
    1321: "Direct hit!",
    1322: "Enemy neutralized.",
    1323: "Is everyone alright?",
    1324: "No injuries.",
    1325: "Good. Keep moving.",
    1326: "The executive suite is just ahead.",
    1327: "Kandori is waiting.",
    1328: "Brace yourselves for a tough fight.",
    1329: "We're with you all the way.",
    1330: "For our school, and for Maki!",
    1331: "Let's do this!",

    # 101-150
    1332: "Kandori: So, you have finally arrived, little rats.",
    1333: "Did you honestly believe you could challenge a god?",
    1334: "Maki: Kandori! What did you do to my mother?!",
    1335: "Kandori: Setsuko Sonomura? She was merely a stepping stone for my research.",
    1336: "Reiji: You bastard! I'm going to rip you apart with my bare hands!",
    1337: "Kandori: Ah, Reiji. Still as vulgar as ever.",
    1338: "Show me what you have learned from your worthless struggles!",
    1339: "Nanjo: State your reason for bringing demons into our world!",
    1340: "Kandori: Reason? To cast aside this decaying reality and birth a new world order!",
    1341: "Behold the true power of the Deva System!",
    1342: "The room is warping!",
    1343: "A dimensional rift is expanding!",
    1344: "Stand firm, everyone!",
    1345: "Summon your Personas!",
    1346: "Kandori: Disappear into the void!",
    1347: "We won't lose to the likes of you!",
    1348: "Strike with everything we've got!",
    1349: "All-Out Attack!",
    1350: "Kandori's barrier is breaking!",
    1351: "One more strike!",
    1352: "Kandori: Impossible... How could mere children...?!",
    1353: "The Deva System is overloading!",
    1354: "We're being sucked into the rift!",
    1355: "Hold on to each other!",
    1356: "Maki, grab my hand!",
    1357: "Everything's turning white...!",
    1358: "Where... where are we?",
    1359: "Is this... Mikage-cho?",
    1360: "Something feels terribly wrong.",
    1361: "The sky looks strange...",
    1362: "The town... It looks like an alternate Mikage-cho.",
    1363: "Maki: This is... the world of my heart.",
    1364: "The dream world created by the Deva System.",
    1365: "We have to find a way back to the real world.",
    1366: "Let's look around for clues.",
    1367: "First, let's head to St. Hermelin High.",
    1368: "Maybe someone there knows what happened.",
    1369: "Agreed. Let's move.",
    1370: "The streets are eerie.",
    1371: "People are acting as if nothing happened.",
    1372: "They don't realize this world is fake.",
    1373: "How terrifying...",
    1374: "Stay alert for shadows.",
    1375: "Here is the school gate.",
    1376: "Let's go inside.",
    1377: "Everything looks normal on the surface.",
    1378: "Let's check the library.",
    1379: "Kurokawa might be there.",
    1380: "Look, there he is.",
    1381: "Kurokawa: Ah, hey guys! Did you read the new issue of Occult Monthly?",

    # 151-200
    1382: "Kurokawa: There's this crazy article about parallel dimensions!",
    1383: "Mark: Not now, Kurokawa! We need real info!",
    1384: "Kurokawa: Fine, fine~ No need to shout.",
    1385: "Have you seen that girl in black wandering around the school?",
    1386: "She gives off such a creepy vibe.",
    1387: "Maki: A girl in black...?",
    1388: "Could it be Aki?!",
    1389: "We have to find her!",
    1390: "Where did she go, Kurokawa?",
    1391: "Kurokawa: Toward the gymnasium, I think.",
    1392: "Let's check the gym!",
    1393: "Wait, let's look around the 1st floor first.",
    1394: "Check the teachers' lounge.",
    1395: "Principal Oishi: Ahem! All students must abide by school regulations!",
    1396: "Vice Principal Sori: Exactly! No unauthorized wanderings!",
    1397: "Nanjo: Those two are as oblivious as ever.",
    1398: "Let's head to the gymnasium.",
    1399: "The dressing rooms are back here.",
    1400: "What's going on?",
    1401: "Ballet Club Member: Kyaaa! A peeping tom!",
    1402: "Mark: Who are you calling a peeping tom?!",
    1403: "I was just looking for someone!",
    1404: "Ballet Club Member: Pervert! Get out, get out!",
    1405: "Yukino: Mark, quit causing a scene!",
    1406: "Mark: I didn't do nothin'!",
    1407: "Brown: Hehehe, busted, Mark!",
    1408: "Mark: Shut up, Brown!",
    1409: "Ayase: Guys are so hopeless~",
    1410: "Elly: Let us continue our search.",
    1411: "Did anyone see the girl in black?",
    1412: "Student: I saw her heading outside toward the forest.",
    1413: "Forest? There used to be a police station there!",
    1414: "The geography is shifting.",
    1415: "The police station became a forest...",
    1416: "This really is a world made of dreams and memories.",
    1417: "Let's go check the forest.",
    1418: "Before that, let's stop by the infirmary.",
    1419: "Saeko-sensei and Hishimi-sensei are there.",
    1420: "Infirmary Door opens.",
    1421: "Hishimi-sensei: Oh, hello everyone! Are you hurt?",
    1422: "Saeko-sensei: You look troubled. Is something the matter?",
    1423: "Maki: Sensei, do you notice anything strange about the town?",
    1424: "Saeko-sensei: Strange? Everything seems peaceful to me.",
    1425: "Though there have been strange rumors lately.",
    1426: "Take good care of yourselves.",
    1427: "Hishimi-sensei: I have medicine if you need healing!",
    1428: "Restored our health.",
    1429: "Thank you, Sensei.",
    1430: "Let's head outside now.",
    1431: "Off to the shopping mall!",

    # 201-250
    1432: "Sun Mall Shopping District.",
    1433: "Joy Street.",
    1434: "Check the local shops for gear.",
    1435: "Satomi Tadashi Pharmacy.",
    1436: "That catchy tune is playing again!",
    1437: "Sing along with the jingle~",
    1438: "Buy healing items and status cures.",
    1439: "Now let's check the armor boutique.",
    1440: "Mannequin: Welcome to the boutique, cuties~",
    1441: "Looking for fashionable armor?",
    1442: "Ayase: I want a cute miniskirt!",
    1443: "Elly: Something elegant with high defense, please.",
    1444: "Nanjo: Practicality and protection are all that matter.",
    1445: "Mark: Something with 'Number 1' on it, Nanjo?",
    1446: "Nanjo: Silence, Inaba!",
    1447: "Equip the new armor.",
    1448: "Our defense has increased!",
    1449: "Now let's check the weapon shop.",
    1450: "Weapon Clerk: Welcome! Looking for self-defense tools?",
    1451: "Mark: Selling guns and axes with a smiling face... this town is crazy.",
    1452: "Buy swords, guns, and ammo.",
    1453: "Everyone is fully geared up.",
    1454: "Let's talk to the townsfolk for rumors.",
    1455: "Townsperson: Have you visited the old lady who hoards treasures?",
    1456: "They say she dug up artifacts from ancient ruins!",
    1457: "Maki: Ruins? In Mikage-cho?",
    1458: "Let's go investigate her mansion.",
    1459: "Here is the Matsudaira residence.",
    1460: "Yuko Matsudaira: Oh my, what do commoners want with our household?",
    1461: "Looking at our precious family heirlooms?",
    1462: "Mark: We don't care about your junk, lady!",
    1463: "Yuko: How rude! My Doberman John will chase you away!",
    1464: "Maki: Yuko, stop being so arrogant!",
    1465: "Yuko: Hmph! I only invited Maki for tea, not the rest of you!",
    1466: "Nanjo: We have no interest in your tea.",
    1467: "Let us depart.",
    1468: "Brown: Man, she really rubs me the wrong way!",
    1469: "Ayase: She was way nicer in the real world~",
    1470: "Now let's find the old treasure-hunting lady.",
    1471: "Here's her shack.",
    1472: "Old Woman: What do you brats want?!",
    1473: "I don't have any money for debt collectors!",
    1474: "Nanjo: Did you excavate ancient ruins?",
    1475: "Old Woman: None of your business! Get lost!",
    1476: "Maki: She's so grumpy...",
    1477: "Mark: Let's leave her be and check the shrine.",
    1478: "To Alraya Shrine!",
    1479: "The priest at the shrine is praying.",
    1480: "Priest: O youths, the distortion in the world is growing deeper.",
    1481: "Seek the sacred mirror to reveal the truth.",

    # 251-300
    1482: "Maki: The sacred mirror...",
    1483: "The Hama Mirror at the Historical Museum!",
    1484: "Let's head to the Historical Museum.",
    1485: "The museum doors are open.",
    1486: "Look at the exhibits...",
    1487: "Ancient artifacts, folklore, and strange relics.",
    1488: "There's a staircase leading to the basement.",
    1489: "A foul stench is rising from below.",
    1490: "Mark: Ugh! Smells like rotten eggs and sewage!",
    1491: "Elly: Be careful. A powerful demon lurks beneath.",
    1492: "Descend the basement stairs.",
    1493: "A grotesque entity blocks the path!",
    1494: "Yog-Sothoth: Who dares disturb my slumber...?!",
    1495: "Maki: It's the monster from the Lovecraftian books!",
    1496: "Nanjo: Without the Hama Mirror, our attacks cannot pierce its flesh!",
    1497: "We must retrieve the mirror first!",
    1498: "Fall back!",
    1499: "Retreat to the upper floor.",
    1500: "Where is the Hama Mirror kept?",
    1501: "Check the display cases in the main hall.",
    1502: "Case #4 is locked.",
    1503: "Find the curator's key.",
    1504: "Found the Exhibit Key in the office!",
    1505: "Unlock Case #4.",
    1506: "Obtained the 'Hama Mirror'!",
    1507: "Now we can face the basement beast.",
    1508: "Equip the mirror.",
    1509: "Return to the basement.",
    1510: "Hold up the Hama Mirror!",
    1511: "The sacred light illuminates the chamber!",
    1512: "Yog-Sothoth: GYAAARGH! The light burns!!",
    1513: "Its barrier is dispelled!",
    1514: "Attack now!",
    1515: "Persona! Strike its core!",
    1516: "Direct hit!",
    1517: "The demon dissolves into black mist.",
    1518: "We did it!",
    1519: "The basement is clear.",
    1520: "Look, there's a treasure chest behind the altar.",
    1521: "Open the chest.",
    1522: "Obtained rare incense and gems!",
    1523: "Let's head back outside.",
    1524: "The air feels a bit clearer.",
    1525: "Now, let's track down the Black Market.",
    1526: "The entrance to the Black Market is in the alleyway.",
    1527: "Enter the Black Market.",
    1528: "Crowds of delinquents and shady figures.",
    1529: "Chisato Kasai is ruling this place as the 'Harem Queen'!",
    1530: "Maki: Chisato... Why did she become a Queen here?",
    1531: "Nanjo: Because in this dream world, secret desires become reality.",

    # 301-350
    1532: "Let's head to Chisato's palace.",
    1533: "The Haunted Mansion.",
    1534: "Guards block the gate.",
    1535: "Guard: Only those favored by the Queen may enter!",
    1536: "Mark: We're going in whether you like it or not!",
    1537: "Defeat the palace guards.",
    1538: "The gates swing open.",
    1539: "Enter the Haunted Mansion.",
    1540: "Eerie paintings line the corridors.",
    1541: "Look at that portrait...",
    1542: "It's Maki's painting!",
    1543: "Chisato took Maki's artwork and claimed it as her own.",
    1544: "How petty.",
    1545: "Navigate the mansion's traps.",
    1546: "Floor spikes, illusion walls, teleport tiles.",
    1547: "Stay sharp.",
    1548: "Reach the throne room.",
    1549: "Chisato: Welcome, my loyal subjects~",
    1550: "Maki: Chisato, stop this charade!",
    1551: "Chisato: Charade? I am the Queen! Everyone loves and obeys me!",
    1552: "Why would I ever go back to being a plain high school girl?!",
    1553: "Nanjo: Your kingdom is built on sand.",
    1554: "Face reality!",
    1555: "Chisato: Silence! Savor my wrath!",
    1556: "Boss Battle: Harem Queen Chisato!",
    1557: "Break her illusions!",
    1558: "Strike with wind and fire!",
    1559: "Chisato: No... My palace... My beauty...!",
    1560: "Chisato is defeated.",
    1561: "She collapses to her knees.",
    1562: "Maki: Chisato, you don't need a crown to be special.",
    1563: "You're already my precious friend.",
    1564: "Chisato: Maki... I was so jealous of you...",
    1565: "I'm sorry...",
    1566: "She snaps out of her delusion.",
    1567: "The Black Market's seal is lifting.",
    1568: "Maki: Only we seem to have this kind of power.",
    1569: "Nanjo: I doubt Kandori will remain quiet.",
    1570: "What will he attempt next...?",
    1571: "Nanjo: That girl possesses immense power.",
    1572: "If someone were to misuse it, it would be catastrophic.",
    1573: "Mark: No doubt about it.",
    1574: "Mark: It's crystal clear she's no ordinary girl.",
    1575: "Elly: Whatever kind of Demon it may be, it will be fine!",
    1576: "As long as we resolve it together.",
    1577: "Elly: Even if someone looks as sweet as an angel on the outside, it doesn't mean their inside is the same.",
    1578: "Brown: Everywhere we go, it's demons, demons, demons~",
    1579: "Aren't there any more cheerful topics?",
    1580: "Brown: When kids act out too much, their big bro has to step in!",
    1581: "Ayase: This school feels kinda weird.",

    # 351-400
    1582: "Smells strangely like a fake replica.",
    1583: "Ayase: Just as I thought, this place...",
    1584: "No wonder it feels like a knockoff.",
    1585: "Lounging around without even realizing it.",
    1586: "Student: Why is the girl in black targeting this academy?",
    1587: "Does she hold some kind of grudge?",
    1588: "Student: At this point, no matter what happens, nothing surprises me.",
    1589: "For example, what if you could actually control demons too?",
    1590: "...There you go again~!",
    1591: "No way that's true, right~?",
    1592: "Doesn't she resemble someone?",
    1593: "Student: I just remembered.",
    1594: "I've actually met the girl in white before.",
    1595: "Not that it's related, right?",
    1596: "Maki: Does your school's gymnasium have club rooms too?",
    1597: "Nanjo: Truly dilapidated.",
    1598: "I wouldn't be surprised if it collapsed at any moment.",
    1599: "Mark: The curtain is full of holes, but I ain't peeping, dammit!",
    1600: "Elly: The more I look at this town, the more wondrous it is.",
    1601: "It truly feels like a world from the past.",
    1602: "Brown: Tch, so ugly!",
    1603: "They should just tear this place down too!",
    1604: "Ayase: Ayase's never been to a place like this before.",
    1605: "Reiji: I'm not here for your damn sightseeing walk.",
    1606: "Student: Ah! Don't tell me you came to peep on us?!",
    1607: "Mark: D-Don't be stupid! Who'd wanna peep on you lot...?!",
    1608: "Ballet Club Room: If we only had a proper club room, we could change without worrying about peeping toms!",
    1609: "Elly: ...It is futile, Mark. Come, let us go.",
    1610: "Telling them is completely pointless.",
    1611: "Come on, let's move!",
    1612: "Maybe your daily behavior is just too suspicious.",
    1613: "Come on, let's get going already!",
    1614: "Nanjo: Stop fixating on trivial matters, Inaba!",
    1615: "Let us advance.",
    1616: "Student: Ah... That's the girl! The one who took Chisato-san away! She had demons with her too!",
    1617: "Are we going to be left like this...?",
    1618: "Maki: It's gonna be okay! Leave it to us!",
    1619: "Let's hurry!",
    1620: "Student: I've met a girl who looks just like that girl in black before.",
    1621: "Nanjo: There is another girl...?",
    1622: "Student: Probably. You know that place that's a forest now? A while back it was a flower bed, right?",
    1623: "I saw her playing over there.",
    1624: "Mark: Let's see... It used to be a flower bed, and now...",
    1625: "Man, this town makes no damn sense.",
    1626: "The police station Sori was talking about turned into a forest...",
    1627: "Ayase: Speaking of the forest, Sori said the police station turned into a forest, right?",
    1628: "Brown: Speaking of forests, Sori was saying something about that, wasn't he?",
    1629: "Like the police station became a forest.",
    1630: "So that means Sori said the police station's location turned into a forest.",
    1631: "Maki: The police station? We went to rescue Inaba-kun and Nanjo-kun there...",

    # 401-450
    1632: "Come to think of it, it used to be a pretty flower bed, but suddenly turned into a huge forest. I was shocked too.",
    1633: "Student: What are you all muttering about? You guys are acting super suspicious.",
    1634: "Hey, are you guys really St. Hermelin students?",
    1635: "Maki: Hey guys, we have to hurry! Well, we're heading out now, see ya!",
    1636: "Ayase: Demons here too...?",
    1637: "Maki: Let's hurry and find that girl! She must be somewhere in the school!",
    1638: "Nanjo: Why does the girl in black target the school...?",
    1639: "What does she gain from attacking the academy?",
    1640: "Mark: When the hell are we gonna be able to save the real Sonomura...?",
    1641: "Elly: The girl in black is controlling Demons after all...",
    1642: "In that case, we must stay on high alert.",
    1643: "Don't you think leaving two women behind is a bit worrying?",
    1644: "If you want, yours truly can stay here and protect the teachers!",
    1645: "Ayase: Finding the infirmary in a place like this makes me feel so relieved~",
    1646: "Reiji: What's with that terrified teacher?",
    1647: "What's happening right now?",
    1648: "Teacher doesn't know what to do either.",
    1649: "Hey, Saeko-sensei?",
    1650: "She's terrified after all...",
    1651: "Hishimi-sensei: If you get injured, come see me!",
    1652: "Hishimi-sensei: Alright, this should do it.",
    1653: "Teacher: Earlier...",
    1654: "Yuko: Oh my, what business do you all have?",
    1655: "Did you come to see our storehouse treasures?",
    1656: "Sorry to disappoint, but...",
    1657: "Mark: We don't give a damn about your fancy treasures, but don't treat us like thieves!",
    1658: "Yuko: Oh my, did it sound that way? Goodness, how overly sensitive.",
    1659: "I didn't mean it that way at all.",
    1660: "I am feeling a bit unwell.",
    1661: "Would you mind stepping outside?",
    1662: "Brown: Gaaah! That girl is so annoyingly haughty!!",
    1663: "Ayase: Yuko, you were way cuter before, ya know.",
    1664: "I'm heading outside.",
    1665: "Maki: Yuko, that's rude to everyone!",
    1666: "Maki is my friend, but the others aren't!",
    1667: "Maki: Geez, Yuko...",
    1668: "Maki: Alright guys, let's go.",
    1669: "Yuko: Maki, come have some tea at my place! I have a pastry left over for one person.",
    1670: "If you do that, the others will...",
    1671: "Well, this time, together with everyone...",
    1672: "How boring!",
    1673: "...Fine, today is special, so I'll invite everyone.",
    1674: "Yuko: N-No, that's wrong! We have John the Doberman, and the butler...",
    1675: "Nanjo: Hmph. Then once everything is resolved, we shall all come over.",
    1676: "Old Woman: What do you want with my place?",
    1677: "You're not debt collectors, are you?",
    1678: "As you can see, there's no money here!",
    1679: "There weren't any treasures, so business has been dead!",
    1680: "Did she suddenly get rich recently and start a business from ruins?",
    1681: "Maki: Nanjo-kun, please! Grandma says tomb-raiding ruins is her job...",

    # 451-500
    1682: "Elly: Calling tomb-raiding a 'job' is quite a stretch.",
    1683: "Besides, doing such a thing in modern Japan is unheard of.",
    1684: "Maki is saying such strange things...",
    1685: "Brown: Tomb-raiding? How could anyone do that in Japan?! Maki-chan says the weirdest things.",
    1686: "Ayase: Tomb-raiding~? No way anyone has that as a real job~ Sonomura, get a grip~!",
    1687: "Everyone's saying that, right?",
    1688: "Mark: Come to think of it, about a year ago there was a rumor that the old lady got rich from raiding ruins...",
    1689: "...Then again, you're a different Sonomura, after all.",
    1690: "Old Woman: Stop your noisy bickering! If you have no business, get out!",
    1691: "Old Woman: You're still here?! If you have no business, hurry up and leave!",
    1692: "Sonomura said the old woman makes a living from tomb-raiding ruins.",
    1693: "In our town, that was merely a rumor.",
    1694: "Yet in this town, it seems to be reality.",
    1695: "Why did a rumor become reality?",
    1696: "Oh no, my stomach hurts...",
    1697: "Hey everyone, let's get going!",
    1698: "Old Woman: What on earth happened? Suddenly everywhere has turned upside down...",
    1699: "You kids look strong. Seeing this mess, don't you feel like doing something about it?!",
    1700: "Sorry, Grandma, we've been running around trying to sort it out too.",
    1701: "Elly: Mark, calm down... Maki will surely be fine. Come, let us go search quickly!",
    1702: "Maki will surely be fine. Come, let us go search quickly.",
    1703: "It will be fine! Everything will be resolved soon.",
    1704: "It will be fine. Everything should be resolved soon.",
    1705: "Brown: There, there, Mark. Soon enough, we'll fix everything right up!",
    1706: "Just a little more, and everyone will be safe.",
    1707: "Reiji: Calm down, Inaba. Then I'll take care of everyone.",
    1708: "Welcome to the shop★",
    1709: "[Weapon Shop Area]",
    1710: "Maki: The girl in white...",
    1711: "Nanjo: In this town, weapons are exclusively for combating demons.",
    1712: "Which is why there is no need for police.",
    1713: "Mark: No matter how many times I come, I can't get used to someone smiling and asking 'Looking for weapons?'",
    1714: "Elly: All the magazines here are so old, aren't they?",
    1715: "Elly: All the magazines placed here are old, aren't they?",
    1716: "Brown: Huh? This model already retired, right? Why is she on the front cover?",
    1717: "Ayase: No way! Look at this model! Wearing clothes like this... nobody wears that anymore...",
    1718: "Wait, this magazine is super old!",
    1719: "Reiji: What is this shop?",
    1720: "Youth: The place that used to be a pretty flower bed suddenly turned into a forest. Is there some greening movement going on?",
    1721: "Townsperson: A little girl used to play in the flower bed all the time. But now it's a forest... I wonder how she's doing?",
    1722: "That girl was wearing white clothes, such a cute child.",
    1723: "Clerk: Welcome! Are you looking for weapons?",
    1724: "That place over there...",
    1725: "If you're shopping...",
    1726: "It should all be settled soon.",
    1727: "Maki: That lady over there said being too happy makes her anxious.",
    1728: "Isn't having fun every day the best thing ever? Don't you think so too?",
    1729: "Nanjo: I do not mean to be picky, but armor with 'Number 1' on it would be ideal.",
    1730: "Sorry about that.",
    1731: "Mark: My mom's fashion sense is the absolute worst! The other day she bought me a T-shirt with 'Armpit' written on the chest!",

    # 501-615
    1732: "Where does she even buy that kind of stuff?!",
    1733: "Not that my mom is bad or anything...",
    1734: "Elly: I don't know much about armor, but...",
    1735: "Brown: Even if the defense is a bit low, pick something that looks cool for yours truly!",
    1736: "Ayase: Ayase wants a miniskirt~ If the skirt is too long, it's lame!",
    1737: "Townsperson: Living in such a wonderful town, I feel so happy.",
    1738: "But when humans are too happy, it actually makes them anxious.",
    1739: "What if I wake up tomorrow and find out this was all just a dream...?",
    1740: "Mannequin: Welcome~ What kind of outfit are you looking for, handsome?",
    1741: "I can help you with sizing if you like!",
    1742: "That's what they say.",
    1743: "Maki: I've heard of Shibuya, but what's Daikanyama?",
    1744: "Is that a place name?",
    1745: "In your world, there are towns like that too? Hmmm...",
    1746: "Do you think having fun every day is all that matters?",
    1747: "Even if something terrible is brewing behind the scenes, is it better to fool around without knowing?",
    1748: "Mark: Daikanyama is pretty small compared to Shibuya, but lately magazines feature it all the time.",
    1749: "It's got trendy cafes and boutiques.",
    1750: "Nanjo: A town favored by the youth, is it?",
    1751: "A frivolous place, no doubt.",
    1752: "Brown: Hey, Daikanyama is super stylish!",
    1753: "Yours truly would fit right in!",
    1754: "Ayase: Ayase loves Daikanyama! The clothes there are super kawaii~",
    1755: "Elly: It is known for its quiet, refined European-style streets.",
    1756: "Quite a lovely district.",
    1757: "Reiji: Who cares about fashionable streets. Let's move.",
    1758: "Maki: I'd love to visit there someday with everyone!",
    1759: "When this is all over, let's all go together!",
    1760: "Mark: Deal! It's a promise, Maki!",
    1761: "Brown: Group date in Daikanyama, baby!",
    1762: "Ayase: As if Ayase would go on a date with you, Brown~!",
    1763: "Nanjo: Focus on the mission at hand.",
    1764: "The path ahead is fraught with danger.",
    1765: "We cannot afford distractions.",
    1766: "Yukino: Nanjo's right. Keep your eyes on the goal.",
    1767: "Let's check the next area.",
    1768: "The Dimensional Rift near the shrine.",
    1769: "Be ready for a fight.",
    1770: "Here comes an ambush!",
    1771: "Demons incoming!",
    1772: "Take battle positions!",
    1773: "Persona!",
    1774: "Clear the field!",
    1775: "All enemies eliminated.",
    1776: "Good work, team.",
    1777: "The rift is stabilizing.",
    1778: "We're making steady progress.",
    1779: "Keep pressing forward.",
    1780: "Toward the core of the dream.",
    1781: "To save Maki, and wake up our town!",
    1782: "Let's go!",
    1783: "Next sector.",
    1784: "Checking map coordinates.",
    1785: "All clear.",
    1786: "Maintain formation.",
    1787: "No one gets left behind.",
    1788: "Understood!",
    1789: "Forward!",
    1790: "Trish: Welcome to Trish's Spring~!",
    1791: "Want full recovery for HP and SP?",
    1792: "It'll cost ya, of course!",
    1793: "Healing isn't free in this economy, sweetie!",
    1794: "Pay up and get healed, or walk away in pain!",
    1795: "Thank you for your patronage~★",
    1796: "Come back anytime you're bleeding!",
    1797: "Mark: That fairy is a total extortionist!",
    1798: "Nanjo: A necessary expense for our survival.",
    1799: "Brown: My wallet is crying, man!",
    1800: "Ayase: Trish is pretty cute though, even if she's greedy~",
    1801: "Elly: At least her healing magic is genuine.",
    1802: "Reiji: Let's just get this over with.",
    1803: "Agastya Tree: Save your progress?",
    1804: "Game saved successfully.",
    1805: "Continue your journey.",
    1806: "The path to the Deva core awaits.",
    1807: "Stay strong, Persona users.",
    1808: "Victory will be yours.",
    1809: "Let's march on!",
    1810: "For the future!",
    1811: "And for our friends!",
    1812: "Yeah!",
    1813: "Onward!",
    1814: "The end of the dream draws near.",
    1815: "Prepare for the final confrontation."
}

# Update json file
chunk_path = 'scripts/retranslate2/chunks/E2_part_03.json'
with open(chunk_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for e in data['entries']:
    eid = e['id']
    if eid not in t:
        raise ValueError(f"Missing ID {eid}: {e['text_jp']}")
    e['translation_en'] = t[eid]

with open(chunk_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=1)

print(f"[+] Successfully updated {chunk_path} with {len(data['entries'])} translations!")
