#!/usr/bin/env python3
"""
Translation script for scripts/retranslate/chunks/E2_part_03.json
"""
import json
from pathlib import Path

CHUNK_PATH = Path("scripts/retranslate/chunks/E2_part_03.json")

t_map = {}

# Block 00 (IDs 2993..2996)
t_map[2993] = "Hey, you kids!"
t_map[2994] = "Wait your turn and"
t_map[2995] = "line up properly!"
t_map[2996] = "Please head on out in order!"

# Block 01 (IDs 3005..3029)
t_map[3005] = "Nanjo: Is that old gentleman"
t_map[3006] = "speaking in earnest,"
t_map[3007] = "or merely playing the fool...?"
t_map[3008] = "Who in the world"
t_map[3009] = "is this 'Hiroshi' guy?!"
t_map[3011] = "came by to see me!"
t_map[3012] = "Nurse: That's right,"
t_map[3013] = "it's Mr. Hiroshi, isn't it?"
t_map[3014] = "Would you like to ask him?"
t_map[3015] = "is a truly complex matter."
t_map[3016] = "isn't necessarily the case."
t_map[3017] = "The truth hidden behind the facade"
t_map[3018] = "must be brought to light..."
t_map[3019] = "Are you having fun?"
t_map[3020] = "seems to be the name of her grandson."
t_map[3021] = "Mistaken for someone's grandpa,"
t_map[3022] = "and getting called Hiroshi..."
t_map[3023] = "Nurse: Oh?"
t_map[3024] = "You're Maki Sonamura's"
t_map[3025] = "friends, aren't you?"
t_map[3026] = "Mark: Well, uh..."
t_map[3027] = "You came to pay her a visit in the hospital, right?"
t_map[3028] = "Nanjo: Oho~..."
t_map[3029] = "Aren't you a thoughtful bunch?"

# Block 02 (IDs 3047..3082)
t_map[3047] = "In this hospital,"
t_map[3048] = "someone who could keep Maki company..."
t_map[3049] = "doesn't feel like stepping out of her room, eh...?"
t_map[3050] = "Mark: If you're looking for Maki's room,"
t_map[3051] = "it's straight down this hall,"
t_map[3052] = "the second door on the way."
t_map[3054] = "was the right thing to do."
t_map[3055] = "She'll definitely be thrilled!"
t_map[3056] = "Never seen 'em before."
t_map[3057] = "They oughta come out more often."
t_map[3058] = "On this very same floor,"
t_map[3059] = "there's a high school girl"
t_map[3060] = "staying in the ward, but..."
t_map[3061] = "the voice of a little girl"
t_map[3062] = "could be heard from inside..."
t_map[3063] = "It's supposed to be a private room, though."
t_map[3064] = "Did a visitor drop by?"
t_map[3065] = "Or was it something else?"
t_map[3069] = "At a corporation like that,"
t_map[3070] = "could they really be?!"
t_map[3071] = "Damn it!"
t_map[3072] = "I should've brought it with me!"
t_map[3073] = "Can't be helped now!"
t_map[3074] = "She's been waiting eagerly for you."
t_map[3075] = "was delighted."
t_map[3076] = "Over and over,"
t_map[3077] = "she keeps saying that, doesn't she?"
t_map[3078] = "I'm so worried about her..."
t_map[3079] = "Not even coming to visit...!"
t_map[3080] = "SEBEC's business might be"
t_map[3081] = "busy, for all I know, but..."
t_map[3082] = "the poor thing..."

# Block 03 (IDs 3399..3463)
t_map[3399] = "...if we leave it at that..."
t_map[3400] = "we should definitely be able to track it down!"
t_map[3401] = "How thrilling!"
t_map[3402] = "...Pardon my unseemly excitement."
t_map[3403] = "I won't let them get away with this!"
t_map[3404] = "I'll restore everything back to normal!"
t_map[3405] = "I must administer treatment...!"
t_map[3406] = "No reception anywhere,"
t_map[3407] = "and phone calls won't connect at all!"
t_map[3408] = "What on earth has happened?!"
t_map[3409] = "I could have helped them..."
t_map[3410] = "Where it even is,"
t_map[3411] = "I haven't the faintest idea!"
t_map[3412] = "Everything has been totally"
t_map[3413] = "twisted out of shape!"
t_map[3414] = "didn't show up anywhere."
t_map[3415] = "If only we had that!"
t_map[3416] = "Elly: Maki's mother,"
t_map[3417] = "come to the Araya Shrine!"
t_map[3418] = "I have a gut feeling."
t_map[3419] = "It's so suffocating."
t_map[3420] = "is sealed up tight."
t_map[3421] = "It feels like we're surrounded on all sides."
t_map[3422] = "Just like some bizarre horror novel,"
t_map[3423] = "being trapped and unable to leave..."
t_map[3424] = "that can't be real, can it?"
t_map[3425] = "Did you come here to listen?"
t_map[3426] = "I'll tell you something enlightening."
t_map[3427] = "to the truth of the matter."
t_map[3428] = "Not yet, I take it?"
t_map[3433] = "There's nothing we can't accomplish"
t_map[3434] = "with a power like this!"
t_map[3435] = "This power..."
t_map[3436] = "Do the other guys"
t_map[3437] = "possess it as well?"
t_map[3438] = "That is indeed so."
t_map[3439] = "Please do not forget that!"
t_map[3440] = "Seems like it'll prove quite useful."
t_map[3441] = "Patient: Urggghhh..."
t_map[3442] = "The pain is starting to flare up again..."
t_map[3443] = "If we don't reach our destination,"
t_map[3444] = "we won't even receive treatment?!"
t_map[3445] = "I've braced myself, but..."
t_map[3446] = "I'm still so worried..."
t_map[3447] = "They should have arrived by now,"
t_map[3448] = "so hopefully nothing bad has occurred..."
t_map[3449] = "Mark: Is there someone"
t_map[3450] = "suffering in agony?"
t_map[3451] = "her mother's..."
t_map[3452] = "Let's head to the shrine!"
t_map[3453] = "and you see..."
t_map[3454] = "I thought they were frail, but they're surprisingly calm and composed."
t_map[3455] = "I can't get in touch with anyone..."
t_map[3456] = "What should I do?"
t_map[3457] = "Can't you help us somehow?"
t_map[3458] = "I'm so sorry..."
t_map[3459] = "I panicked and got all confused..."
t_map[3460] = "Are you holding up all right?"
t_map[3461] = "Let me have a look..."
t_map[3462] = "I want to rescue as many people as possible."
t_map[3463] = "Just don't push yourself beyond your limits."

# Block 04 (IDs 3913..3917)
t_map[3913] = "Nanjo: Even with money in hand,"
t_map[3914] = "there is nowhere to spend it."
t_map[3915] = "Young Master Nanjo!"
t_map[3916] = "Please put in a word for us!"
t_map[3917] = "We're counting on you!"

# Block 05 (IDs 3939..3951)
t_map[3939] = "Demons are appearing everywhere!"
t_map[3940] = "A whole swarm of them is pouring out!"
t_map[3941] = "Officer...?"
t_map[3942] = "You say...?"
t_map[3943] = "Hold on a moment!"
t_map[3944] = "So many of them showed up..."
t_map[3945] = "And look at this sorry mess..."
t_map[3946] = "Save me..."
t_map[3947] = "Elly: As I suspected!"
t_map[3948] = "Let us make our escape!"
t_map[3950] = "We can't rely on them"
t_map[3951] = "in the slightest, can we!"

# Block 06 & 07 (IDs 4132..4161)
t_map[4132] = "[Weapon Shop]"
t_map[4157] = "[Item Shop]"
t_map[4158] = "Maki: What is it?"
t_map[4159] = "Are you buying something?"
t_map[4161] = "Are you sure this'll be all right?"

# Block 08 (IDs 4167..4187)
t_map[4167] = "What about SEBEC,"
t_map[4168] = "what're we doing about that?"
t_map[4169] = "Are we all done here~?"
t_map[4170] = "Hurry up and"
t_map[4171] = "let's go after Kandori~!"
t_map[4174] = "Let's hurry and get outta here."
t_map[4175] = "A dump like this..."
t_map[4176] = "Do we really gotta go after all?"
t_map[4177] = "It just doesn't suit me,"
t_map[4178] = "being crammed into tight, stuffy spaces!"
t_map[4179] = "Do we really gotta smash 'em?"
t_map[4180] = "It's fine, ain't it?!"
t_map[4182] = "That bastard Kandori..."
t_map[4183] = "We gotta track him down, man...!!"
t_map[4186] = "Why'd they have to put everything under such tight security anyway?"
t_map[4187] = "What an outrageous place that was..."

# Block 09 (IDs 4210..4218)
t_map[4210] = "Inaba-kun"
t_map[4211] = "is at the police station, right?"
t_map[4212] = "Let's go save him!"
t_map[4213] = "We were heading to the abandoned factory,"
t_map[4214] = "wasn't that the plan?"
t_map[4215] = "We've got to pursue him!"
t_map[4217] = "What a totally lame store!"
t_map[4218] = "I'll gear up!"

# Block 10 & 11 (IDs 4228..4251)
t_map[4228] = "I totally love this kind of stuff!"
t_map[4229] = "It's super cute!"
t_map[4231] = "Maki: The owner of this shop"
t_map[4232] = "is pretty terrible at business, isn't he?"
t_map[4233] = "It was my first time doing it!"
t_map[4234] = "I was a little nervous at first, but"
t_map[4235] = "it turned out to be a blast!"
t_map[4237] = "There's a whole bunch of 'em,"
t_map[4238] = "I'll never forgive that jerk!"
t_map[4239] = "Pay close attention,"
t_map[4240] = "I'd never laid eyes on it before, but..."
t_map[4241] = "We simply cannot leave this unattended!"
t_map[4243] = "We're storming right in,"
t_map[4244] = "so we'd better pack some firepower!"
t_map[4245] = "Who knows what crazy stunt he'll pull?"
t_map[4251] = "Yeah! Let's go save him!"

# Block 12 & 13 (IDs 4270..4286)
t_map[4270] = "Elly,"
t_map[4271] = "you sure are popular with everyone..."
t_map[4272] = "There are dime-a-dozen clowns"
t_map[4273] = "like that everywhere!"
t_map[4279] = "Mark: While we're wasting time here,"
t_map[4280] = "won't he do something reckless?"
t_map[4283] = "He's not that soft of a guy,"
t_map[4284] = "is he now!"
t_map[4286] = "It really leaves you speechless."

# Block 14 (IDs 4712..4735)
t_map[4712] = "I've never been here before!"
t_map[4713] = "When it comes to poker, I'm pretty confident!"
t_map[4714] = "Why not let us have a crack at it?"
t_map[4715] = "Are they not thinking at all,"
t_map[4716] = "or what? I can't fathom it."
t_map[4717] = "'Cause we gotta get moving."
t_map[4718] = "The air in here is terrible."
t_map[4719] = "I just love the slot machines here!"
t_map[4720] = "is really unusual, you know?"
t_map[4722] = "I don't wanna keep nagging,"
t_map[4723] = "but don't you forget it!"
t_map[4724] = "Ain't no demon 'round here!"
t_map[4725] = "If it were a demon,"
t_map[4726] = "I'da vanquished it in a flash, sheesh!"
t_map[4727] = "I'll make 'em"
t_map[4728] = "into my minions!"
t_map[4729] = "What are we gonna do...?"
t_map[4730] = "There's no way we can beat a demon!"
t_map[4731] = "I'm terrified, man!"
t_map[4732] = "Don't chick out on me!"
t_map[4733] = "While they're away,"
t_map[4734] = "I left you"
t_map[4735] = "in charge, didn't I?!"

# Block 15 (IDs 5145..5161)
t_map[5145] = "about my"
t_map[5146] = "mother, that's what I'm talking about."
t_map[5147] = "Who are you talking about?"
t_map[5150] = "about your mother,"
t_map[5151] = "can't you remember anything yet?"
t_map[5152] = "Seems like there's some complicated history behind it."
t_map[5155] = "Can we really gain entry into SEBEC?"
t_map[5156] = "We must pursue him...!"
t_map[5158] = "I almost got a scratch on my gorgeous face!"
t_map[5159] = "I almost broke the hearts"
t_map[5160] = "of every single Brown fan out there!"
t_map[5161] = "I totally despise getting shots, though!"

# Block 16 (IDs 5227..5238)
t_map[5227] = "I don't really"
t_map[5228] = "wanna stick around here."
t_map[5229] = "Isn't there any stage"
t_map[5230] = "where we can really show off our skills?"
t_map[5231] = "Am I standing out properly?"
t_map[5236] = "crawling all over the place"
t_map[5237] = "must be SEBEC's fault too."
t_map[5238] = "I can't stand the smell of disinfectant in here~"

# Block 17 (IDs 5313..5342)
t_map[5313] = "Let's go help them out."
t_map[5314] = "What is that?"
t_map[5315] = "A place like that,"
t_map[5316] = "was there ever one around...?"
t_map[5317] = "Let's go after him!"
t_map[5318] = "I'm finally"
t_map[5319] = "getting into the groove!"
t_map[5320] = "I'll show 'em what I've got!"
t_map[5321] = "It appears you have"
t_map[5322] = "completely forgotten."
t_map[5323] = "Nanjo: Don't you think Maki's behavior"
t_map[5324] = "is rather peculiar?"
t_map[5325] = "Hmm..."
t_map[5329] = "I also"
t_map[5330] = "heard rumors about a strange shop"
t_map[5331] = "some time ago."
t_map[5333] = "Opening a shop like that,"
t_map[5334] = "is clearly suspicious, isn't it?"
t_map[5335] = "Speaking of that odd establishment,"
t_map[5336] = "it seems it's about to open."
t_map[5337] = "I wonder what kind of business they run?"
t_map[5338] = "Word is they're already open for business."
t_map[5339] = "Western music"
t_map[5340] = "can be heard wafting from inside."
t_map[5341] = "Could it be a members-only club?"
t_map[5342] = "I'd sure love to take a look inside..."

# Block 18 (IDs 5392..5410)
t_map[5392] = "I don't think it's necessary, but..."
t_map[5393] = "Is it truly that important?"
t_map[5398] = "I want to unravel this mystery."
t_map[5402] = "We go in,"
t_map[5403] = "we take down Kandori, right?"
t_map[5404] = "That's how it's gonna play out, ain't it?"
t_map[5405] = "We gotta chase him down,"
t_map[5406] = "or we're in serious trouble..."
t_map[5407] = "Saying we can't fight,"
t_map[5408] = "is that what it means?"
t_map[5409] = "Could something like that"
t_map[5410] = "really be taking place?"

# Block 19 (IDs 5494..5523)
t_map[5494] = "[Convenience Store]"
t_map[5495] = "Weapons,"
t_map[5496] = "they don't sell them here?"
t_map[5497] = "That's weird~"
t_map[5498] = "Isn't it obvious why not?"
t_map[5499] = "All the essentials"
t_map[5500] = "are in stock right here."
t_map[5501] = "Is this where she works part-time,"
t_map[5502] = "or was it somewhere else?"
t_map[5503] = "can serve as weapons"
t_map[5504] = "in a pinch, you know."
t_map[5506] = "Guns and stuff,"
t_map[5507] = "they're super scary, right?"
t_map[5508] = "Customer: Modern convenience stores"
t_map[5509] = "have everything on their shelves!"
t_map[5510] = "Saying it's absurd"
t_map[5511] = "That's exactly right!"
t_map[5512] = "to consumer needs,"
t_map[5513] = "you've got to cater!"
t_map[5515] = "They sell everything under the sun, don't they?!"
t_map[5516] = "Not stocking weapons"
t_map[5517] = "is completely ridiculous!"
t_map[5518] = "Don't you agree?!"
t_map[5519] = "You took the words right out of my mouth!"
t_map[5520] = "meet consumer demand,"
t_map[5521] = "isn't that your responsibility?!"
t_map[5522] = "Do you carry weapons"
t_map[5523] = "in this establishment?"

# Block 20 (IDs 5902..5905)
t_map[5902] = "Patrol the school grounds!"
t_map[5903] = "All information"
t_map[5904] = "must not be leaked,"
t_map[5905] = "we cannot allow it!"

# Block 21 (IDs 5925..5930)
t_map[5925] = "Kido-san"
t_map[5926] = "went outside,"
t_map[5927] = "or so it seems!"
t_map[5928] = "It was my golden chance to talk to him,"
t_map[5929] = "and now it's ruined~!"
t_map[5930] = "Come on back!"

# Block 22 (IDs 5953..5963)
t_map[5953] = "I bet if"
t_map[5954] = "I show off my good side,"
t_map[5955] = "she might fall for me, right?"
t_map[5958] = "Man, that guy is bad news."
t_map[5959] = "He's completely off his rocker."
t_map[5960] = "Ayase-san,"
t_map[5961] = "he's been stalking her around,"
t_map[5962] = "and that type of guy,"
t_map[5963] = "when they obsess over someone, it's seriously creepy~"

# Block 23 (IDs 5985..5988)
t_map[5985] = "It was true all along!"
t_map[5986] = "They aren't coming in here, right?"
t_map[5987] = "Demons and all that,"
t_map[5988] = "are you talking in your sleep?"

# Block 24 (IDs 6018..6048)
t_map[6018] = "You went outside, didn't you?"
t_map[6019] = "You're still in one piece?"
t_map[6020] = "Tamaki-chan: Aha~"
t_map[6021] = "You're scared, aren't you?"
t_map[6022] = "Why don't you go look for yourself?"
t_map[6023] = "Coward Tadashi!"
t_map[6024] = "Shut up, you idiot!"
t_map[6025] = "You're WAY scarier,"
t_map[6026] = "you muscle-brained maniac!"
t_map[6028] = "You big chicken!"
t_map[6030] = "You meathead!"
t_map[6031] = "That's hard to say..."
t_map[6032] = "You think so too, don't you?"
t_map[6033] = "Tamaki-chan: *pant* *pant* *pant*..."
t_map[6034] = "Take this."
t_map[6035] = "For certain reasons, it's what I used to fight with at my old school..."
t_map[6036] = "This time, it's your turn, not mine."
t_map[6037] = "At least, that's what my gut tells me..."
t_map[6038] = "Some of them can actually be reasoned with."
t_map[6039] = "Fighting isn't the only way forward."
t_map[6040] = "The name of the demon prowling outside,"
t_map[6041] = "she called it on the first try!"
t_map[6042] = "Like which ones can be reasoned with,"
t_map[6043] = "and which ones won't become 'allies'..."
t_map[6044] = "What's an 'ally'?"
t_map[6047] = "A terrible calamity is unfolding, isn't it..."
t_map[6048] = "Received the Rapier!"

# Block 25 (IDs 6060..6063)
t_map[6060] = "Could this really be"
t_map[6061] = "the curse of the Karma Mansion?"
t_map[6063] = "It definitely is!"

# Block 26 (IDs 6097..6108)
t_map[6097] = "I don't have to go to cram school!"
t_map[6098] = "We can't even"
t_map[6099] = "go back home, huh...?"
t_map[6100] = "If only there was an exit,"
t_map[6101] = "we could slip right out~"
t_map[6103] = "You have absolutely no idea"
t_map[6104] = "what kind of danger we're in!"
t_map[6105] = "Forget about taking entrance exams,"
t_map[6106] = "our whole lives"
t_map[6107] = "might be completely over!"
t_map[6108] = "It's so bright..."

# Block 27 (IDs 6257..6269)
t_map[6257] = "It'll be over soon, right?"
t_map[6258] = "If that happens,"
t_map[6259] = "it'd really suck!"
t_map[6260] = "On the door,"
t_map[6261] = "a lock has been placed..."
t_map[6262] = "Hey you!"
t_map[6263] = "You're still in a place like this?!"
t_map[6264] = "The gymnasium is being locked down,"
t_map[6265] = "so head back to the main school building!"
t_map[6266] = "Demons have broken into the school grounds."
t_map[6267] = "It wouldn't be surprising if they came in here too."
t_map[6268] = "Well, that can't be possible, surely."
t_map[6269] = "Hurry up and get out!"

# Block 28 & 29 (IDs 6310..6371)
t_map[6310] = "It's just one hardship after another."
t_map[6311] = "And now we get this mess..."
t_map[6312] = "In the art club,"
t_map[6313] = "it was the entire school after all."
t_map[6314] = "I'm so relieved."
t_map[6367] = "We're cursed, aren't we?!"
t_map[6368] = "It's a curse, I tell ya!"
t_map[6369] = "Maybe we can go grab a bite to eat!"
t_map[6370] = "I knew it, this is terrifying!"
t_map[6371] = "It won't open!"

# Block 30 to 34 (IDs 6401..6571)
t_map[6401] = "They're manufacturing biological weapons, I hear!"
t_map[6436] = "talking like that,"
t_map[6437] = "this ain't the time for it!"
t_map[6438] = "When the heck"
t_map[6439] = "wanna make a bet with me?"
t_map[6474] = "So it was an illusion after all."
t_map[6475] = "That blue room"
t_map[6476] = "didn't have anything to do with it, it seems..."
t_map[6518] = "Right over there,"
t_map[6519] = "it's locked tight."
t_map[6559] = "With all that massive uproar outside,"
t_map[6560] = "it's so peaceful in here..."
t_map[6561] = "Demons won't"
t_map[6562] = "appear in this place, right?"
t_map[6563] = "Could it be divine protection?"
t_map[6564] = "Philemon Stone"
t_map[6565] = "An ancient megalith excavated locally,"
t_map[6566] = "its mineral composition is Samarskite, however"
t_map[6567] = "magnetic anomalies have been detected."
t_map[6568] = "It is said an entity known as Philemon,"
t_map[6569] = "as a guardian stone for Mikage-cho,"
t_map[6570] = "descended from the heavens to bestow upon us,"
t_map[6571] = "according to local lore."

# Block 35 (IDs 7027..7049)
t_map[7027] = "SEBEC Employee: This company..."
t_map[7028] = "I knew there was something shady going on behind the scenes, but..."
t_map[7029] = "To think they were actually developing biological weapons!"
t_map[7030] = "SEBEC Employee: The other day in the office,"
t_map[7031] = "wearing black clothes,"
t_map[7032] = "I saw the shadow of a little girl..."
t_map[7033] = "It must be the curse of the Karma Mansion!"
t_map[7034] = "Yes!"
t_map[7035] = "That's got to be it!!"
t_map[7036] = "Maki: The Karma Mansion, huh..."
t_map[7037] = "I used to sneak over there to play all by myself..."
t_map[7038] = "Mark: Biological weapons~?!"
t_map[7039] = "Completely turning an entire corporation into his personal toy,"
t_map[7040] = "what the hell is he planning?!"
t_map[7042] = "What he's doing is the absolute lowest!"
t_map[7044] = "Even if they got biological weapons,"
t_map[7045] = "as long as we're around, they'll go down in one hit!"
t_map[7046] = "Elly: A mansion where a ghost appears...?"
t_map[7047] = "Does such a place really exist?"
t_map[7048] = "Ayase: How long do you guys plan"
t_map[7049] = "on dragging your feet?!"

# Block 36 (IDs 7070..7088)
t_map[7070] = "Receptionist: Huh?"
t_map[7072] = "You came from the basement?"
t_map[7073] = "I heard there was a secret division down in the basement that's classified even to employees..."
t_map[7074] = "Are you folks from down there?"
t_map[7075] = "It won't open."
t_map[7076] = "Maki: Secrets that even the company employees"
t_map[7077] = "know nothing about..."
t_map[7078] = "What kind of company is this?"
t_map[7079] = "Mark: He's grinning like a smug jerk!"
t_map[7081] = "Nanjo: They say fools and smoke always favor high places."
t_map[7082] = "Let us head for the top floor!!"
t_map[7083] = "How totally lame~!"
t_map[7085] = "Knowing nothing about it,"
t_map[7086] = "Just kidding~!"
t_map[7087] = "We have no time to be fooling around!"
t_map[7088] = "Ayase: We ain't got time to be loafing around!"

# Block 37 (IDs 7109..7132)
t_map[7109] = "SEBEC Employee: High schoolers wearing"
t_map[7110] = "the exact same uniform as you kids"
t_map[7111] = "passed through here just a moment ago..."
t_map[7112] = "On the day of our company tour,"
t_map[7113] = "for a disaster like this to strike..."
t_map[7114] = "SEBEC Employee: Who on earth did this?!"
t_map[7115] = "Rearranging the rooms without telling me"
t_map[7116] = "and turning it into a giant warehouse?!"
t_map[7117] = "And cramming weird toys"
t_map[7118] = "in here on top of that!"
t_map[7119] = "I will not let this stand!!"
t_map[7120] = "Maki: These people too,"
t_map[7121] = "they're victims as well, aren't they?"
t_map[7122] = "Mark: Let's find Kandori fast!"
t_map[7123] = "Seems like they're completely in the dark."
t_map[7125] = "I wonder who that was?"
t_map[7127] = "What are they doing?"
t_map[7128] = "Not that I'm one to talk, though."
t_map[7129] = "Elly: Other students from our school,"
t_map[7130] = "besides ourselves?"
t_map[7131] = "Who on earth could that be?"
t_map[7132] = "With the receptionist,"

# Block 38 (IDs 7155..7174)
t_map[7155] = "Maki: We have to restore the town back to normal!"
t_map[7156] = "To think we can wield Personas..."
t_map[7157] = "Mark: As long as we take care of Kandori,"
t_map[7158] = "the town oughta return to normal too!"
t_map[7159] = "Mark: Let's hurry up"
t_map[7160] = "and chase down Kandori!"
t_map[7161] = "Nanjo: In a place like this,"
t_map[7162] = "we have no time to be idling about."
t_map[7166] = "Let's go!"
t_map[7168] = "You mean you had a dream about a butterfly?"
t_map[7170] = "There is no turning back for Kandori."
t_map[7172] = "You're saying you had a dream about a butterfly?"
t_map[7173] = "Elly: Let us make haste."
t_map[7174] = "Did you happen to dream of a butterfly?"

# Block 39 (IDs 7257..7273)
t_map[7257] = "My heart's pounding!"
t_map[7258] = "Looks like we can get inside."
t_map[7259] = "I don't mind if you turn back."
t_map[7260] = "I'll take that guy down!"
t_map[7261] = "I'll take care of it, but..."
t_map[7262] = "Elly: Inside SEBEC,"
t_map[7263] = "that is where they are, is it not?"
t_map[7264] = "To make matters all the more dramatic,"
t_map[7265] = "...this has become quite intriguing!"
t_map[7267] = "Let us"
t_map[7268] = "run wild for a bit!"
t_map[7269] = "Ayase and the gang,"
t_map[7270] = "we're high school students, right?"
t_map[7271] = "You liar~!"
t_map[7272] = "They were dead serious,"
t_map[7273] = "weren't they?!"

# Block 40 (IDs 7308..7325)
t_map[7308] = "Welcome to the Healing Spring!"
t_map[7309] = "All wounded allies,"
t_map[7310] = "depending on your cash, can all be Recovered!"
t_map[7311] = "What's your order~?"
t_map[7312] = "Trish: Well now~"
t_map[7313] = "healing market rates lately"
t_map[7314] = "for everyone would be..."
t_map[7315] = "I'll heal you up!"
t_map[7316] = "Drink up~!"
t_map[7317] = "You're good to go!"
t_map[7318] = "Need anything else?"
t_map[7319] = "You don't have enough cash?!"
t_map[7320] = "I hate broke people!"
t_map[7321] = "Come again~"
t_map[7322] = "If you drop dead, don't blame me!"
t_map[7324] = "I'll be waiting for you~"
t_map[7325] = "You called me when you didn't even need anything?!"

# Block 41 (IDs 7367..7411)
t_map[7367] = "Saying you know..."
t_map[7368] = "what are you talking about...?"
t_map[7369] = "I really and truly"
t_map[7370] = "don't have a mother"
t_map[7371] = "or anything like that!"
t_map[7372] = "what on earth is he doing?"
t_map[7373] = "Those rumors about SEBEC,"
t_map[7374] = "they weren't bogus after all!"
t_map[7375] = "Something that could be made public,"
t_map[7376] = "there was never anything like that here, I suppose."
t_map[7378] = "Ain't there anything useful"
t_map[7379] = "lying around this place?!"
t_map[7381] = "There's a distinctly suspicious box right here..."
t_map[7382] = "Down in the basement,"
t_map[7383] = "isn't there one?"
t_map[7384] = "It's right here!"
t_map[7385] = "By the time we got here,"
t_map[7386] = "danger had already found us..."
t_map[7387] = "Please be safe!"
t_map[7388] = "Did he use"
t_map[7389] = "that machine...?"
t_map[7390] = "Scientist: Good heavens!"
t_map[7391] = "It doesn't look like it'll open..."
t_map[7392] = "Maki: A student from St. Hermelin"
t_map[7393] = "had snuck in here,"
t_map[7394] = "it seems!"
t_map[7395] = "Unforgivable!"
t_map[7396] = "their own"
t_map[7397] = "Are they even feeling it?"
t_map[7398] = "A device that creates..."
t_map[7399] = "Was he having them construct such a machine?"
t_map[7400] = "Give me a break..."
t_map[7401] = "Between what we understand"
t_map[7402] = "and what we don't,"
t_map[7403] = "there's way too much confusing stuff going on!"
t_map[7405] = "Who could that be~?"
t_map[7406] = "Are you buddies with that high schooler from earlier?"
t_map[7407] = "What could they possibly accomplish?"
t_map[7408] = "Demons emerging..."
t_map[7409] = "was completely unforeseen."
t_map[7410] = "It is an intriguing phenomenon,"
t_map[7411] = "wouldn't you agree?"

# Block 42 (IDs 7418..7461)
t_map[7418] = "I feel like there is."
t_map[7419] = "Letting that guy get away,"
t_map[7420] = "I will not allow it!"
t_map[7421] = "Defeat him,"
t_map[7422] = "and we can set everything back to how it was..."
t_map[7423] = "I'll turn everything back to normal myself!"
t_map[7424] = "The humming of large machinery,"
t_map[7425] = "can't you hear it?"
t_map[7426] = "If only we had someone"
t_map[7427] = "on our side like that too."
t_map[7428] = "The absolute worst! Thinking only of your research,"
t_map[7429] = "and nothing else!"
t_map[7430] = "Staying in a safe place,"
t_map[7431] = "as demon prey,"
t_map[7432] = "do you intend to leave us?!"
t_map[7433] = "I can't see it..."
t_map[7434] = "Just when I thought,"
t_map[7435] = "currying favor,"
t_map[7436] = "that's what you were up to?!"
t_map[7437] = "Ruined!"
t_map[7438] = "My vital research is...!"
t_map[7440] = "What on earth is"
t_map[7441] = "this company doing?"
t_map[7443] = "didn't sit right with me."
t_map[7444] = "into his schemes,"
t_map[7445] = "I went along, but..."
t_map[7446] = "I don't care, but..."
t_map[7447] = "every time I think she's gonna burst into tears,"
t_map[7448] = "it gets on my nerves..."
t_map[7449] = "What on earth"
t_map[7450] = "is going to happen?"
t_map[7451] = "I look forward to finding out!"
t_map[7452] = "Let us pursue him!"
t_map[7453] = "That guy named Kandori,"
t_map[7454] = "let's go smash him to pieces!"
t_map[7455] = "Think we're getting cold feet?"
t_map[7456] = "No way in hell!"
t_map[7457] = "Do we really gotta"
t_map[7458] = "chase after him...?"
t_map[7459] = "I'm not scared"
t_map[7460] = "Actually, it's pretty freaky..."
t_map[7461] = "I can't see it..."

# Block 43 (IDs 7468..7519)
t_map[7468] = "[Boutique]"
t_map[7469] = "She offered to hire bodyguards for me, so demons wouldn't attack."
t_map[7470] = "That's impossible, though."
t_map[7471] = "It costs an arm and a leg!"
t_map[7472] = "I'm terribly sorry."
t_map[7473] = "working a part-time job,"
t_map[7474] = "she was supposed to be such a devoted girl, but..."
t_map[7475] = "That's Chisato Himeno, right?"
t_map[7476] = "Did my eyes deceive me?"
t_map[7477] = "Was she always... that kind of person?"
t_map[7478] = "Hanging out with"
t_map[7479] = "people like that?"
t_map[7480] = "Associating with them"
t_map[7481] = "isn't exactly what I'd call it."
t_map[7482] = "Is she talking about us?!"
t_map[7484] = "That it's NOT about us"
t_map[7485] = "is plainly obvious!"
t_map[7488] = "Was her personality always that nasty~?"
t_map[7489] = "I could have sworn I heard"
t_map[7490] = "'people like that' just now..."
t_map[7491] = "Surely I must have misheard?"
t_map[7492] = "These guys may be"
t_map[7493] = "a bunch of utterly hopeless fools,"
t_map[7494] = "and might fit the bill of 'people like that', but..."
t_map[7495] = "hearing an outsider say it,"
t_map[7496] = "why does it irk me so...?"
t_map[7497] = "Did she eat something bad?"
t_map[7498] = "Mark: What the hell"
t_map[7499] = "is 'people like that' supposed to mean?!"
t_map[7500] = "that's what I'm thinking!"
t_map[7501] = "Elly: Lacking that much confidence"
t_map[7502] = "is taking it a bit too far."
t_map[7503] = "That can't be Himeno! She wasn't that kind of girl!"
t_map[7504] = "Himeno: You need something?"
t_map[7505] = "Don't speak to me!"
t_map[7506] = "Being friends with a girl like that,"
t_map[7507] = "she'd be better off ditching her."
t_map[7508] = "Those two are friends, aren't they?"
t_map[7509] = "[Boutique]"
t_map[7510] = "She was crazy gorgeous, wasn't she~..."
t_map[7511] = "Why don't you get kidnapped in her place?"
t_map[7512] = "To think she went missing..."
t_map[7513] = "By the god of fate,"
t_map[7514] = "she seems to be hated."
t_map[7515] = "She was really good at drawing."
t_map[7516] = "Elly: The girl in black..."
t_map[7517] = "She is shrouded in mystery."
t_map[7518] = "I wonder if he liked her?"
t_map[7519] = "No matter how you look at it,"


def main():
    with open(CHUNK_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    entries = data.get("entries", [])
    print(f"Total entries in chunk: {len(entries)}")
    print(f"Total translated entries defined: {len(t_map)}")
    
    missing = []
    for e in entries:
        eid = e["id"]
        if eid not in t_map:
            missing.append((eid, e.get("text_jp", "")))
        else:
            e["translation_en"] = t_map[eid]
            
    if missing:
        print(f"ERROR: Missing translations for {len(missing)} entries!")
        for eid, txt in missing[:20]:
            print(f"  ID {eid}: {txt}")
        return
        
    with open(CHUNK_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print("SUCCESS: Successfully wrote translated chunk back to file!")

if __name__ == "__main__":
    main()
