#!/usr/bin/env python3
"""
Translation script for scripts/retranslate/chunks/E0_part_08.json
Megami Ibunroku Persona (PSX, 1996) English Localization.
"""
import json
from pathlib import Path

CHUNK_PATH = Path("scripts/retranslate/chunks/E0_part_08.json")

t_map = {}

# ==============================================================================
# Batch 1: IDs 8347..8363 (entries 0..16) - Gingerbread House / Charm
# ==============================================================================
t_map[8347] = "She's crying deep inside..."
t_map[8348] = "Maki: The real me..."
t_map[8349] = "...can only be saved by..."
t_map[8350] = "...the ideal me..."
t_map[8351] = "Maki's Mother: To think that child was..."
t_map[8352] = "...the ideal Maki..."
t_map[8353] = "Maki's Mother: Huh?"
t_map[8354] = "When Maki was little,"
t_map[8355] = "it's a little charm I taught her."
t_map[8356] = "Her father passed away so early,"
t_map[8357] = "and I was always busy with work,"
t_map[8358] = "so she was always all alone..."
t_map[8359] = "I told her to chant this spell whenever she was lonely in the hospital..."
t_map[8360] = "'Because Mama will always feel Maki-chan, no matter where I am...'"
t_map[8361] = "Please, try saying it backwards."
t_map[8362] = "Because she is my treasure..."
t_map[8363] = "...slotted into place."

# ==============================================================================
# Batch 2: IDs 8367..8438 (entries 17..82) - Maki's Breakdown & Nanjo's Speech
# ==============================================================================
t_map[8367] = "It's your mother!!"
t_map[8368] = "Let's go home together!"
t_map[8369] = "Everyone was so worried about you,"
t_map[8370] = "they came all this way for you!"
t_map[8371] = "Maki: Stay away!!"
t_map[8372] = "Why did you come?!"
t_map[8373] = "You know what kind of girl I really am,"
t_map[8374] = "don't you?!"
t_map[8375] = "Telling you not to sweat it might be asking too much,"
t_map[8376] = "I guess, but..."
t_map[8377] = "getting jealous of people is something everyone feels, right?"
t_map[8378] = "Even I feel that way!"
t_map[8379] = "Sonomura was just being used! Kandori's the bad guy here, ain't he?"
t_map[8380] = "Maki: How many times..."
t_map[8381] = "...did I try to kill everyone?!"
t_map[8382] = "Why are you all being so nice to me?!"
t_map[8383] = "Stop pitying me!"
t_map[8384] = "Being pitied just makes me feel more miserable..."
t_map[8385] = "It'd be better if I just died!"
t_map[8386] = "Mark: That ain't true at all!"
t_map[8387] = "Nanjo: You spoiled brat..."
t_map[8389] = "Even you..."
t_map[8390] = "...think so too, don't you?!"
t_map[8391] = "Nanjo: Stop acting like a spoiled brat!!"
t_map[8392] = "You reap what you sow!!"
t_map[8393] = "Deal with your own mess yourself!!"
t_map[8394] = "If you want to die that badly,"
t_map[8395] = "why are you still standing there?"
t_map[8396] = "Don't go screaming about things you won't even follow through on!"
t_map[8397] = "Don't make me laugh."
t_map[8398] = "Because we sympathized with you,"
t_map[8399] = "we came all this way of our own accord."
t_map[8400] = "Do you honestly think you live entirely on your own?"
t_map[8401] = "You are allowed to live"
t_map[8402] = "by the grace of the people around you!"
t_map[8403] = "You have a responsibility!"
t_map[8404] = "Your thoughtless, easy choices"
t_map[8405] = "will leave an indelible scar"
t_map[8406] = "on the hearts of countless people for the rest of their lives!"
t_map[8407] = "Go ahead and forget everything."
t_map[8408] = "But we will never forget."
t_map[8409] = "We will never forget you, our comrade."
t_map[8410] = "We're going back."
t_map[8411] = "We're going to save Sonomura."
t_map[8412] = "This sentimental nonsense is not my style."
t_map[8413] = "Everyone..."
t_map[8414] = "Please, take me with you too..."
t_map[8415] = "Hell yeah, of course we will!"
t_map[8416] = "Elly: Welcome back,"
t_map[8417] = "Maki-chan!"
t_map[8418] = "I'm home!"
t_map[8419] = "Maki's Mother: *sob*..."
t_map[8423] = "I was such a bad girl..."
t_map[8424] = "I remembered..."
t_map[8425] = "It was so painful..."
t_map[8426] = "I resented everything..."
t_map[8428] = "Maki-chan..."
t_map[8429] = "Maki: I'm so sorry..."
t_map[8431] = "My apologies."
t_map[8432] = "I spoke rather harshly."
t_map[8433] = "Are you blushing?!"
t_map[8434] = "Oh, I get it!"
t_map[8435] = "He's such a sourpuss, after all!"
t_map[8436] = "Quiet, Inaba!"
t_map[8437] = "Good grief..."
t_map[8438] = "Let's head back!"

# ==============================================================================
# Batch 3: IDs 8445..8474 (entries 83..105) - Reassurance & Gratitude
# ==============================================================================
t_map[8445] = "My eyes are wide open now."
t_map[8446] = "Even if I'm only a shadow, I'm still me, after all..."
t_map[8447] = "Because I have"
t_map[8448] = "you and everyone else..."
t_map[8449] = "Nothing could be more reassuring than that..."
t_map[8450] = "Guess I come in handy"
t_map[8451] = "once in a blue moon, eh?"
t_map[8452] = "Nanjo: Hmph."
t_map[8453] = "Receiving gratitude from others is hardly something to boast about."
t_map[8454] = "Reiji: ...We don't have time"
t_map[8455] = "to stand around basking in warm fuzzies."
t_map[8456] = "Elly: I'm so glad..."
t_map[8457] = "Even if something like that were to happen to me..."
t_map[8458] = "I'm saying such strange things, but..."
t_map[8459] = "You'll definitely come save me, right?"
t_map[8460] = "If it's you..."
t_map[8464] = "You will surely come rescue me, won't you?"
t_map[8467] = "We're tearing up over here..."
t_map[8468] = "You came down so hard on her,"
t_map[8469] = "I thought things were gonna go completely haywire!"
t_map[8472] = "Maki's Mother: I don't even know"
t_map[8473] = "how to begin thanking all of you..."
t_map[8474] = "Maki is truly so fortunate."

# ==============================================================================
# Batch 4: IDs 8611..8724 (entries 106..158) - Alaya Shrine / Sea of Souls Prep
# ==============================================================================
t_map[8611] = "That Philemon guy!"
t_map[8665] = "Only the two of you may proceed."
t_map[8666] = "Are your preparations thorough?"
t_map[8667] = "Are your weapons and items in order?"
t_map[8668] = "Will you enter the inner shrine?"
t_map[8669] = "Then,"
t_map[8670] = "I shall open the path to the Sea of Consciousness."
t_map[8671] = "A path has opened behind the shrine."
t_map[8672] = "Go forth."
t_map[8674] = "Return once your preparations are complete."
t_map[8675] = "Are you fully prepared?"
t_map[8676] = "Regroup with your companions."
t_map[8677] = "Will you regroup with your companions?"
t_map[8678] = "Philemon: Return when your preparations are finished."
t_map[8679] = "Philemon: If you intend to go outside,"
t_map[8680] = "do not forget to"
t_map[8681] = "regroup with your companions."
t_map[8682] = "We're counting on ya!"
t_map[8683] = "We'll be waiting right here!"
t_map[8684] = "Don't go overdoing it."
t_map[8685] = "We're heading out!"
t_map[8686] = "Just 'cause you're alone with Sonomura,"
t_map[8687] = "don't go losing your head, got it?!"
t_map[8688] = "Maki: What are you two talking about?"
t_map[8689] = "Just girl talk, that's all."
t_map[8690] = "Maki: That sounds kinda naughty..."
t_map[8691] = "Mark: Sonomura looks..."
t_map[8692] = "...pretty happy, doesn't she?"
t_map[8693] = "Why couldn't I go with 'em?"
t_map[8694] = "Nanjo: Stay on your guard."
t_map[8695] = "There is no telling what lies ahead."
t_map[8696] = "Nanjo: Where are you going?"
t_map[8697] = "I do not mind, but"
t_map[8698] = "we do not have much time to spare."
t_map[8699] = "She's happy..."
t_map[8701] = "Reiji: ...I want to"
t_map[8702] = "go toe-to-toe with you sometime."
t_map[8703] = "Don't you dare die on me."
t_map[8704] = "Reiji: Still haven't left?"
t_map[8705] = "Elly: Where are you going?"
t_map[8706] = "If it's where you're going,"
t_map[8707] = "I'll gladly follow, but..."
t_map[8708] = "Elly: Where are you going?"
t_map[8710] = "I shall accompany you, but..."
t_map[8711] = "Please be careful..."
t_map[8712] = "We'll be waiting for you..."
t_map[8714] = "I shall be waiting..."
t_map[8716] = "Best of luck!"
t_map[8718] = "You still haven't gone?"
t_map[8719] = "Don't tell me you're chickening out?"
t_map[8720] = "You haven't gone yet?"
t_map[8721] = "Getting cold feet?"
t_map[8724] = "Make sure you go see Sonomura!"

# ==============================================================================
# Batch 5: IDs 8737..8866 (entries 159..204) - Sea of Souls Judgment
# ==============================================================================
t_map[8737] = "Mysterious Voice: ..."
t_map[8738] = "Here, you..."
t_map[8739] = "...stood by and watched a pitiful woman die..."
t_map[8740] = "'As long as I survive, that's all that matters...'"
t_map[8741] = "Can you honestly swear"
t_map[8742] = "that you didn't think that?"
t_map[8745] = "Without regard for your own safety,"
t_map[8746] = "you saved a pitiful woman..."
t_map[8753] = "You tried to abandon an old man who had been used..."
t_map[8755] = "Rather than defeat Kandori, you chose the path of saving the old man..."
t_map[8770] = "Did you believe the contents of the box were more important?"
t_map[8771] = "Succumbing to the terror of being turned to stone,"
t_map[8772] = "you claim you did not bend your principles..."
t_map[8773] = "Can you hold your chest high and honestly swear that?"
t_map[8775] = "Refusing to yield to threats,"
t_map[8776] = "standing firm in your true convictions..."
t_map[8777] = "That is no easy feat to accomplish..."
t_map[8778] = "..."
t_map[8779] = "..."
t_map[8781] = "Maki's mother's..."
t_map[8785] = "What if it were her mother...?"
t_map[8788] = "You do not possess"
t_map[8789] = "the eyes to see through to the truth..."
t_map[8790] = "Judging solely by what the eyes can see,"
t_map[8791] = "you refuse to perceive things with your heart..."
t_map[8793] = "You possess the eyes of the heart..."
t_map[8794] = "Not only do you see with your eyes,"
t_map[8795] = "you know how to perceive things with your heart..."
t_map[8813] = "And you were lost in doubt..."
t_map[8814] = "You..."
t_map[8815] = "...could not save a soul crying out for salvation..."
t_map[8816] = "Because your own soul"
t_map[8817] = "was lost in doubt as well."
t_map[8821] = "You granted peace..."
t_map[8822] = "Because in your own soul,"
t_map[8823] = "there was no word of hesitation."
t_map[8855] = "You think so too, don't you?!"
t_map[8857] = "To her question,"
t_map[8858] = "how did you answer?"
t_map[8859] = "Was your inability to tell her 'don't run away'"
t_map[8860] = "because you knew deep down"
t_map[8861] = "that you were running away yourself?"
t_map[8863] = "You answered her."
t_map[8864] = "Running away is easy..."
t_map[8865] = "If one keeps running away..."
t_map[8866] = "You know the truth..."

# ==============================================================================
# Batch 6: IDs 8980..9087 (entries 205..261) - Shadow Protagonist & Items
# ==============================================================================
t_map[8980] = "Huh...?"
t_map[8981] = "There's two of you?!"
t_map[8982] = "Playing video games in a place like this?!"
t_map[8983] = "Shut up already."
t_map[8984] = "It's my business, ain't it?"
t_map[8985] = "Shadow: That's right."
t_map[8986] = "If you don't believe me,"
t_map[8987] = "I can tell ya everything from your underwear size"
t_map[8988] = "to your exact taste in women!"
t_map[8989] = "Shadow: I'm you."
t_map[8990] = "Everything you've ever done,"
t_map[8991] = "what kind of person you really are—"
t_map[8992] = "I know it all..."
t_map[9012] = "I'm your mirror reflection."
t_map[9013] = "You're me, and I'm you."
t_map[9014] = "And it ain't just me."
t_map[9015] = "Deep inside your heart,"
t_map[9016] = "there's thousands upon thousands of other yous."
t_map[9017] = "So stop bothering me."
t_map[9018] = "If you're me, you oughta understand how I feel."
t_map[9019] = "Playing games is total bliss. Getting dragged into troublesome crap"
t_map[9020] = "is the last thing I wanna do."
t_map[9021] = "See ya."
t_map[9022] = "Maki: Who do you think you are, talking down to him like that?!"
t_map[9023] = "He's a wonderful person!"
t_map[9025] = "It's not like there's no hope for you."
t_map[9026] = "Shadow: ...Looks like"
t_map[9027] = "I can't break into you."
t_map[9028] = "Inside that body of yours,"
t_map[9029] = "you're firmly, solidly rooted."
t_map[9030] = "That's proof of just how tough your resolve is."
t_map[9031] = "Shadow: Here."
t_map[9032] = "Take this with you."
t_map[9033] = "To master this,"
t_map[9034] = "it's the key to awakening the ultimate Persona"
t_map[9035] = "sealed deep inside your heart. Go ask that old geezer Igor."
t_map[9036] = "Just remember that the me you saw here"
t_map[9037] = "is still a part of who you are."
t_map[9038] = "Don't you ever forget that."
t_map[9039] = "You're already plenty strong."
t_map[9042] = "With you and that little lady,"
t_map[9052] = "With you and all your friends,"
t_map[9060] = "Shadow: What's the matter?"
t_map[9061] = "There really are all kinds of different sides to yourself, huh."
t_map[9062] = "Maki: Let's hurry and get going!"
t_map[9063] = "Received the"
t_map[9064] = "Rosetta Stone!"
t_map[9065] = "Rosetta Stone"
t_map[9066] = "Received the Passe!"
t_map[9068] = "Purifying Water"
t_map[9069] = "Tortoiseshell Glasses"
t_map[9070] = "Babylonian Coffin"
t_map[9075] = "Contract of Judgment"
t_map[9084] = "Received the Stuffed Deer!"
t_map[9085] = "You're so noisy."
t_map[9086] = "Hurry up and beat it."
t_map[9087] = "Looks like a total blast!!"

# ==============================================================================
# Batch 7: IDs 9094..9149 (entries 262..291) - Real Maki Confrontation & Blue Compact
# ==============================================================================
t_map[9094] = "Maki: I finally found you!"
t_map[9095] = "The real me!"
t_map[9096] = "Maki: Wait!"
t_map[9097] = "There's nowhere left for you to run!"
t_map[9098] = "Those countless soap bubbles..."
t_map[9099] = "...are the countless consciousnesses of various people..."
t_map[9100] = "Human consciousness..."
t_map[9101] = "...is nothing more than fragile soap bubbles"
t_map[9102] = "born from this vast sea..."
t_map[9103] = "A consciousness that should never"
t_map[9104] = "have been born in the first place..."
t_map[9105] = "If you had been the one born from the very start, life would have been so different..."
t_map[9106] = "Maki: Stop it!!"
t_map[9107] = "I don't want to hear words like that"
t_map[9108] = "coming out of my own mouth!!"
t_map[9110] = "All you ever do is cry in bed, don't you?!"
t_map[9111] = "Don't you feel anything when you look at everyone?!"
t_map[9112] = "That it isn't—"
t_map[9113] = "That is your true heart!"
t_map[9138] = "I won't run away anymore... I'll take responsibility"
t_map[9139] = "for my own actions!"
t_map[9140] = "Take this with you..."
t_map[9141] = "With this, you can enter the Avidya Realm"
t_map[9142] = "where Pandora is waiting."
t_map[9143] = "You were the one person"
t_map[9144] = "I never wanted to see me looking like this..."
t_map[9145] = "Maki: I wonder if I got through to her..."
t_map[9147] = "Right now, we just have to believe in ourselves..."
t_map[9148] = "Let's head back to everyone!"
t_map[9149] = "Obtained the Blue Compact!"

# ==============================================================================
# Batch 8: IDs 9199..9227 (entries 292..316) - Regrouping Outside Alaya
# ==============================================================================
t_map[9199] = "Maki: Sorry to keep you all waiting!"
t_map[9200] = "Mark: Man, we've been waiting forever!"
t_map[9202] = "Looks like things went smoothly."
t_map[9203] = "Let's head to the school"
t_map[9204] = "to confront this Pandora."
t_map[9205] = "Maki: Looks like everyone"
t_map[9206] = "was really worried about us."
t_map[9207] = "Hey, [Hero]!"
t_map[9208] = "You didn't try pulling anything funny, did ya?"
t_map[9210] = "Did something happen in there?"
t_map[9211] = "Reiji: Looks like you made it back alive..."
t_map[9212] = "Once this mess is cleaned up,"
t_map[9213] = "you and I are settling our score."
t_map[9214] = "You ain't gonna say no, are ya?"
t_map[9215] = "Thank goodness~"
t_map[9216] = "You're not hurt or anything, are you?"
t_map[9217] = "What a relief..."
t_map[9219] = "Tough as nails, ain't ya?"
t_map[9220] = "I figured the script was gonna have you get beat,"
t_map[9221] = "and then the rest of us make a gallant entrance!"
t_map[9222] = "Guess that scenario went straight into the trash, huh."
t_map[9223] = "I seriously thought you were a goner!"
t_map[9225] = "Philemon: Before this world vanishes completely,"
t_map[9226] = "there is precious little time left."
t_map[9227] = "Make haste."

# ==============================================================================
# Batch 9: IDs 9258..9337 (entries 317..381) - St. Hermelin / Final Door Prep
# ==============================================================================
t_map[9258] = "You're safe!"
t_map[9259] = "You're all safe!"
t_map[9260] = "There's nobody here?!"
t_map[9261] = "Yosuke: We don't get it either."
t_map[9262] = "By the time we got back,"
t_map[9263] = "everyone was already gone."
t_map[9264] = "Most of the town has completely vanished too,"
t_map[9265] = "so what on earth is happening—"
t_map[9266] = "we're the ones who want to know!"
t_map[9267] = "Nanjo: This is Pandora's handiwork..."
t_map[9268] = "Everyone... this is all..."
t_map[9269] = "...because of me..."
t_map[9270] = "Yosuke: ...So that's what happened."
t_map[9271] = "I promise you that I"
t_map[9272] = "will return everything to the previous world!"
t_map[9273] = "No matter how much I apologize,"
t_map[9274] = "I know it can never make up for it, but..."
t_map[9275] = "I am truly, truly sorry."
t_map[9276] = "You really are so clumsy... You've always been that way since way back..."
t_map[9277] = "Chisato: The one who should apologize"
t_map[9278] = "is me, not you..."
t_map[9279] = "Calling me into this world was because"
t_map[9280] = "you considered me your best friend, wasn't it?"
t_map[9281] = "I betrayed you... I'm the one who needs to be forgiven, aren't I...?"
t_map[9282] = "Our positions are completely the opposite."
t_map[9285] = "So we don't hold you back,"
t_map[9286] = "we'll wait right here."
t_map[9287] = "Once everything is settled peacefully..."
t_map[9288] = "...let's all go to the amusement park together!"
t_map[9289] = "Maki: ...Yeah!"
t_map[9290] = "Sounds good to me!"
t_map[9291] = "Let's get this over with quick!"
t_map[9292] = "Open the door."
t_map[9293] = "Maki: Okay."
t_map[9294] = "Let's go!"
t_map[9295] = "Elly: It opened!"
t_map[9297] = "Everyone!"
t_map[9299] = "Let's hurry inside!"
t_map[9300] = "Maki: Beyond this door,"
t_map[9301] = "the absolute worst part of me is waiting..."
t_map[9302] = "This is the grand finale, then."
t_map[9303] = "That compact... it may be symbolic of the three primary colors of light."
t_map[9304] = "It can take on any color."
t_map[9305] = "It all depends on oneself... Perhaps that is what it means."
t_map[9306] = "Reiji: Hurry up and go."
t_map[9307] = "I'll take care of whatever comes."
t_map[9308] = "Elly: The time has finally come..."
t_map[9309] = "Elly: It's finally time."
t_map[9310] = "Let's go to the amusement park together!"
t_map[9311] = "I want to ride the Ferris wheel!"
t_map[9313] = "We're gonna hit 'em with our"
t_map[9314] = "Persona Wonderful Bomber!"
t_map[9316] = "Free Fall is the best!"
t_map[9317] = "We did 5 rounds in a row last time,"
t_map[9318] = "so next time it's 10 in a row!"
t_map[9319] = "You're riding with me, got it?!"
t_map[9325] = "Chisato: Be careful, okay?"
t_map[9326] = "My, aren't you quite the ladykiller~"
t_map[9327] = "Who you're in love with right now—"
t_map[9328] = "I can tell in a single glance!"
t_map[9333] = "And... what's... more..."
t_map[9334] = "Looks like it isn't just Maki..."
t_map[9335] = "Yosuke: Hang in there!"
t_map[9336] = "We can't do anything to fight,"
t_map[9337] = "but we're rooting for you!"

# ==============================================================================
# Batch 10: IDs 9502..9543 (entries 382..419) - Avidya Realm / Pandora Boss
# ==============================================================================
t_map[9502] = "Maki: Everyone at this school too..."
t_map[9503] = "...the real me"
t_map[9504] = "imagined them all, right?"
t_map[9505] = "Mark: It's awful quiet around here."
t_map[9506] = "Not a sign of anyone."
t_map[9507] = "It's the library!"
t_map[9508] = "Reiji: This school, this town..."
t_map[9509] = "Once I took out Kandori,"
t_map[9510] = "I didn't care what happened to 'em..."
t_map[9511] = "Or so I thought..."
t_map[9512] = "Now, I love this place."
t_map[9513] = "Because this is the place where I met all of you..."
t_map[9514] = "Do I like it?"
t_map[9515] = "I used to think it was such a suffocating place,"
t_map[9516] = "but now, I truly love it."
t_map[9519] = "I love school!"
t_map[9520] = "Studying ain't my strong suit, sure,"
t_map[9521] = "but studying ain't all there is to life!"
t_map[9522] = "I kinda like it, I guess."
t_map[9523] = "I can pretty much do whatever I want, y'know!"
t_map[9526] = "Pandora: *Hiss...*"
t_map[9527] = "Me?!"
t_map[9528] = "Nanjo: That is—!!"
t_map[9529] = "What lies behind that fiend..."
t_map[9530] = "Is that the DEVA System's core?!"
t_map[9531] = "Pandora: At last..."
t_map[9532] = "you have made it all the way here..."
t_map[9533] = "I have finally seized it..."
t_map[9534] = "I will yield it to no one..."
t_map[9535] = "I shall create a paradise."
t_map[9536] = "A paradise where nothing exists at all..."
t_map[9537] = "That is..."
t_map[9538] = "That is no 'Door to Paradise'!"
t_map[9539] = "It will bring ruin upon this world—"
t_map[9540] = "It is 'Pandora's Box'!"
t_map[9541] = "Everything is pointless..."
t_map[9542] = "Pointless things have no need to exist..."
t_map[9543] = "Disappear into nothingness...!"

# ==============================================================================
# Batch 11: IDs 9606..9645 (entries 420..455) - Defeat of Pandora & Farewell
# ==============================================================================
t_map[9606] = "You won't give up?"
t_map[9607] = "How can all of you..."
t_map[9608] = "...remain so strong?"
t_map[9609] = "Maki: Deep down,"
t_map[9610] = "you understand why, don't you?"
t_map[9611] = "Reiji: Because..."
t_map[9612] = "...we're not alone."
t_map[9613] = "Elly: Because"
t_map[9614] = "we are 'We'..."
t_map[9615] = "Because we are not alone!"
t_map[9618] = "Because we're not alone!"
t_map[9620] = "Because we are not alone!"
t_map[9622] = "Because we're not alone!"
t_map[9623] = "And besides,"
t_map[9624] = "we believe in ourselves!"
t_map[9625] = "A person cannot live alone."
t_map[9626] = "Standing right there..."
t_map[9627] = "Maki: Both you and I..."
t_map[9628] = "...we're all friends."
t_map[9629] = "Let's do our best together!"
t_map[9630] = "Pandora: Thank you..."
t_map[9631] = "Nanjo: It is over..."
t_map[9632] = "Mark: Yeah..."
t_map[9633] = "We have to say goodbye, but..."
t_map[9634] = "I will never, ever forget you..."
t_map[9635] = "Goodbye...?"
t_map[9636] = "As Maki's shadow, I cannot go with everyone..."
t_map[9637] = "I had so much fun..."
t_map[9638] = "Whoa—!!"
t_map[9639] = "Maki: I'm returning everyone..."
t_map[9640] = "...to the real world..."
t_map[9641] = "Can I have a moment?"
t_map[9642] = "Maki: Thank you..."
t_map[9643] = "Even if it's just once in a while,"
t_map[9644] = "please remember me..."
t_map[9645] = "I love you so much..."

# ==============================================================================
# Batch 12: IDs 9647..9686 (entries 456..492) - Epilogue: Graduation Rumors
# ==============================================================================
t_map[9647] = "Hey, [Hero]~"
t_map[9648] = "...Really?!"
t_map[9649] = "Nanjo: Good grief..."
t_map[9650] = "They say you cannot put a door to the world's gossip,"
t_map[9651] = "and yet,"
t_map[9652] = "nothing is more clamorous"
t_map[9653] = "than women gossiping."
t_map[9654] = "I got so tired of waiting!"
t_map[9655] = "Man, I went through pure hell just now!"
t_map[9656] = "Even though I told 'em"
t_map[9657] = "that I don't have"
t_map[9658] = "any second buttons left!"
t_map[9659] = "And they were hunting for you"
t_map[9660] = "with blood in their eyes, too!"
t_map[9661] = "Nanjo: 'A wise man keeps clear of danger.'"
t_map[9662] = "Take heed of that."
t_map[9663] = "Is that right..."
t_map[9664] = "Elly: You all"
t_map[9665] = "are so popular, it must be quite exhausting."
t_map[9667] = "Being such heartthrobs must be tough!"
t_map[9668] = "Sorry to jump right into it, but"
t_map[9669] = "you're keeping us company!"
t_map[9670] = "Don't you dare leave me behind!"
t_map[9671] = "You wouldn't wait for us anyway!"
t_map[9672] = "Everything that happened back then feels like a dream..."
t_map[9673] = "Mark: Say what?"
t_map[9674] = "You're still on about that?"
t_map[9675] = "From that 'Box of Calamity',"
t_map[9676] = "what came out at the very end..."
t_map[9677] = "I was just remembering it..."
t_map[9678] = "Mark: What the heck is that supposed to mean?"
t_map[9679] = "You?"
t_map[9680] = "That's totally cho-very-good!"
t_map[9682] = "You think so~?"
t_map[9683] = "Inaba said, y'know~"
t_map[9685] = "You better remember!"
t_map[9686] = "We're riding it till we drop!"

# ==============================================================================
# Batch 13: IDs 9689..9762 (entries 493..545) - Free Fall Banter & Ending
# ==============================================================================
t_map[9689] = "For all your complaining,"
t_map[9691] = "you're giving me the creeps!"
t_map[9692] = "Heard you're terrified of heights!"
t_map[9693] = "Where'd you hear that?!"
t_map[9694] = "Bragging away with his big mouth, saying this'll be the last time!"
t_map[9695] = "Hearing you bawling and screaming your head off..."
t_map[9696] = "I'm gonna enjoy every single second of it!"
t_map[9697] = "Nanjo: Oho."
t_map[9698] = "This is intriguing news indeed."
t_map[9699] = "I shall observe the proceedings with great interest."
t_map[9700] = "Mark: That bastard!"
t_map[9701] = "He never does anything good!"
t_map[9702] = "What the hell are you laughing at?!"
t_map[9703] = "That's it! Call it off!"
t_map[9704] = "I'm not going!"
t_map[9705] = "Maki: Sorry to keep you waiting~!"
t_map[9706] = "Everyone!"
t_map[9707] = "Nanjo: You arrived at just the right moment."
t_map[9708] = "It appears Inaba wishes to cancel our excursion."
t_map[9709] = "Why?!"
t_map[9710] = "And I was looking forward to it so much!"
t_map[9713] = "Maki: Yay!"
t_map[9715] = "You just wait and see!"
t_map[9716] = "Sonomura..."
t_map[9717] = "It feels like a dream..."
t_map[9718] = "You're still rambling on about that?"
t_map[9722] = "What's that supposed to mean?"
t_map[9723] = "Maki's Voice: Hurry up~!"
t_map[9724] = "There she is!"
t_map[9726] = "You can act all tough now,"
t_map[9727] = "but that ends today!"
t_map[9728] = "Heard you're super-duper"
t_map[9729] = "terrified of high places!"
t_map[9730] = "You little bedwetter!"
t_map[9731] = "Where the hell did you hear that?!"
t_map[9733] = "I heard all about it"
t_map[9734] = "straight from your mom!"
t_map[9735] = "Back in 6th grade, wasn't it?!"
t_map[9736] = "Mark: That damn old hag!"
t_map[9738] = "That's way better than crapping"
t_map[9739] = "your pants in class!"
t_map[9741] = "Today I'm gonna get a front-row seat"
t_map[9742] = "to the pants-wetting scene of the century!"
t_map[9743] = "Nanjo: Good grief, you two..."
t_map[9746] = "Mark was saying"
t_map[9747] = "he's just itching to ride Free Fall"
t_map[9748] = "as fast as possible!"
t_map[9749] = "Maki: Is that so?!"
t_map[9750] = "Let's hurry and go!"
t_map[9752] = "Maki: What's wrong?"
t_map[9755] = "It really feels like a dream..."
t_map[9757] = "You're so mean~"
t_map[9762] = "Wait up for me~!"

def main():
    with open(CHUNK_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    missing = []
    for entry in data["entries"]:
        eid = entry["id"]
        if eid in t_map:
            entry["translation_en"] = t_map[eid]
        else:
            missing.append((eid, entry["offset"], entry["text_jp"]))

    if missing:
        print(f"ERROR: {len(missing)} entries missing translations:")
        for m in missing:
            print(f"  Missing: ID={m[0]}, Offset={m[1]}, JP={m[2]}")
        return False

    with open(CHUNK_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    print(f"Successfully translated all {len(data['entries'])} entries in {CHUNK_PATH}")
    return True

if __name__ == "__main__":
    main()
