#!/usr/bin/env python3
"""
scripts/retranslate/translate_e2_part_02.py
Translates all entries for E2_part_02.json.
"""

import json
from pathlib import Path

translations = {
    # Batch 1: IDs 1902 - 1980 (Town / Casino / NPC / Party banter)
    1902: "You head down that narrow alley,",
    1903: "so it might be a little hard to find, but...",
    1904: "Shopkeeper: Are you students from St. Hermelin?",
    1905: "Do you know my Motoko?",
    1906: "...or so they say!",
    1907: "He fell completely head over heels!",
    1908: "Welcome!",
    1909: "I'm just so worried about it...",
    1910: "That's fine and all, but!",
    1911: "You think it's weird too, don't you?",
    1912: "About that pharmacy!",
    1913: "It's so bizarre!",
    1914: "Shopkeeper: Well, well?",
    1915: "Could it be a lie?",
    1916: "She should be at club practice.",
    1917: "With Tamaki-chan...",
    1918: "I'd love to have a little lover's spat with Tamaki-chan~",
    1920: "Over here!",
    1921: "How about it?",
    1922: "You really can't",
    1923: "judge by appearances, can you.",
    1924: "Nanjo: What a simpleton.",
    1925: "To have that kind of carefree leeway,",
    1926: "I almost envy him.",
    1927: "He's a real celebrity, huh!",
    1928: "If a guy's good-looking,",
    1929: "I guess that's only natural, though.",
    1930: "I don't hate it, but...",
    1931: "I'd like to head to the shrine first.",
    1932: "Whatever you do,",
    1933: "I don't really mind, but...",
    1934: "Could you wait until after we go to the hospital?",
    1935: "Fearless...",
    1936: "I'm just appalled.",
    1937: "He looks like that on the outside, you know.",
    1938: "People of this sort...",
    1939: "It simply cannot be...",
    1940: "Clerk: Welcoooome~",
    1941: "Exchange of money and coins",
    1942: "is handled right here~",
    1943: "Would you like to exchange money for coins?",
    1944: "Clerk: Over here,",
    1945: "exchanging coins for items",
    1946: "is available...",
    1947: "Hey big bros,",
    1948: "are you students?",
    1949: "You know that girl, right?",
    1950: "Mary, or something...",
    1951: "that's what she's called...",
    1952: "She's real pretty, isn't she?",
    1953: "Introduce me next time!",
    1954: "I was looking for you.",
    1955: "Don't just wander around aimlessly!",
    1956: "I was thinking",
    1957: "I'd protect you!",
    1959: "Thank you very much...",
    1960: "Compared to you,",
    1961: "I have plenty of knowledge,",
    1962: "and I can protect myself,",
    1963: "so I shall be quite fine!",
    1964: "Is that so...",
    1965: "She's not here?",
    1966: "And here I thought she would be...",
    1967: "Guess our hunch was wrong.",
    1968: "Sooner or later,",
    1969: "she'll speak up!",
    1970: "All you gotta do is make your move!",
    1971: "Agaaaain...",
    1972: "I blew through all my coins again!",
    1973: "If a big win hits,",
    1974: "then you really strike it rich, huh~",
    1975: "Wait, are you",
    1976: "planning to play next?!",
    1977: "No fair~!",
    1978: "Looks like it's out of order...",
    1979: "Current number of coins:",
    1980: "coins.",

    # Batch 2: IDs 1981 - 2082 (Poker rules & Extra Game / Double Up)
    1981: "There are.",
    1982: "What will you do?",
    1983: "Which explanation would you like to see?",
    1984: "A poker game where you can exchange cards",
    1985: "only once.",
    1986: "At the start, 5 cards",
    1987: "are dealt.",
    1988: "Select the cards you wish to keep",
    1989: "with the D-Pad,",
    1990: "and press 〇, ✕, △, or ▢",
    1991: "to HOLD them.",
    1992: "Once you've decided which cards to HOLD, press R1 or R2 to re-DRAW,",
    1993: "and the unheld cards will be replaced.",
    1994: "After the re-DRAW,",
    1995: "if a winning hand is made, you win.",
    1996: "The higher your bet,",
    1997: "the higher the payout (ODDS)",
    1998: "when a winning hand is completed.",
    1999: "When a winning hand is made,",
    2000: "you can challenge the Extra Game",
    2001: "to gamble your payout.",
    2002: "Please select SCORE.",
    2003: "There are 3 types of Extra Games,",
    2004: "and winning any of them",
    2005: "doubles your payout each time.",
    2006: "Extra Game payouts can be challenged",
    2007: "up to a maximum of 1,000,000 coins.",
    2008: "However, failing even once",
    2009: "forfeits all your winnings from that round,",
    2010: "so please be careful.",
    2011: "[Extra Game 1]",
    2012: "1 face-up card and 4 face-down cards",
    2013: "are displayed on screen.",
    2014: "From the 4 face-down cards,",
    2015: "pick one with a higher rank than the face-up card.",
    2016: "If the chosen card and the face-up card have equal rank, it's a draw",
    2017: "and you get a retry.",
    2018: "[Extra Game 2]",
    2020: "1 face-down card is displayed on screen.",
    2021: "Guess whether the face-down card is",
    2022: "higher or lower than the face-up card.",
    2023: "If the card matches the face-up card's rank, it counts as a loss,",
    2024: "so please be careful.",
    2025: "[Extra Game 3]",
    2028: "If you think it's Hearts or Diamonds, select RED;",
    2029: "if you think it's Spades or Clubs,",
    2030: "select \"BLACK\".",
    2031: "If your chosen color matches the card's color,",
    2032: "you win.",
    2033: "Insert 1 coin.",
    2034: "Cancel HELD cards.",
    2035: "[When a Hand is Made]",
    2036: "Challenge \"HI & LOW\".",
    2037: "Confirm card to reveal.",
    2038: "[When Winning Extra Game] Continue to challenge.",
    2039: "Cancel",
    2040: "the bet coins.",
    2042: "Without challenging the Extra Game,",
    2043: "cash out payout coins.",
    2045: "[When Winning Extra Game] End the Extra Game and cash out.",
    2049: "[When Winning Extra Game] Do not cash out.",
    2053: "Start the game.",
    2054: "Exchange cards",
    2055: "that are not HELD.",
    2058: "Quit Poker game.",
    2061: "Select card.",
    2064: "A hand consisting of",
    2065: "two pairs of matching cards (Two Pair).",
    2066: "A hand consisting of",
    2067: "three cards of the same rank (Three of a Kind).",
    2068: "A hand with five sequential cards",
    2069: "in order (Straight).",
    2070: "A hand with five cards all of the same suit (Flush).",
    2071: "Three of a Kind plus a pair of the remaining two cards (Full House).",
    2073: "Four cards of the same rank (Four of a Kind).",
    2074: "A Straight hand where",
    2075: "all five cards share the same suit (Straight Flush).",
    2076: "Four of a Kind with a Joker (Five of a Kind).",
    2077: "A Flush composed of 10, J, Q, K, and A (Royal Flush).",
    2078: "*In this Poker game,",
    2079: "*For Straight hands,",
    2080: "A cannot connect in sequence to 2.",
    2081: "acts as a wild card,",
    2082: "substituting for any missing card in any hand.",

    # Batch 3: IDs 2088 - 2205 (Blackjack rules & hands)
    2088: "A Blackjack game where you compete",
    2089: "one-on-one against the dealer.",
    2090: "The computer acts",
    2091: "as the dealer.",
    2092: "Two cards each are dealt to the player and the dealer.",
    2093: "One of the dealer's two cards is dealt face-down.",
    2094: "Only when the dealer's face-up card is an Ace,",
    2095: "can you choose to take",
    2096: "INSURANCE.",
    2097: "Regarding INSURANCE,",
    2098: "it will be explained toward the end",
    2099: "of the rules.",
    2100: "First, compare your cards with the dealer's and decide whether to draw another card.",
    2101: "Select \"HIT\" to draw another card, or \"STAND\" to stay.",
    2102: "As long as your card total does not exceed 21,",
    2103: "you may keep drawing cards.",
    2104: "In the following cases,",
    2105: "you will automatically STAND:",
    2106: "*When the initial 2 cards form a Blackjack",
    2107: "*When cards drawn from the 3rd onward",
    2108: "reach a total of 21",
    2109: "*When you have drawn 7 cards",
    2110: "*When the card total",
    2111: "exceeds 21 (Bust)",
    2112: "Cards 2~10 are counted at face value,",
    2113: "J~K count as 10,",
    2114: "and A counts as either 1 or 11,",
    2115: "whichever is advantageous.",
    2116: "After the player STANDs, the dealer draws cards.",
    2117: "As long as the player's total does not exceed 21,",
    2118: "if your total is higher than the dealer's",
    2119: "or if the dealer busts,",
    2120: "the player wins.",
    2121: "If both sides",
    2122: "have Blackjack,",
    2123: "the bet coins",
    2124: "are refunded (Push).",
    2125: "In addition to HIT and STAND,",
    2126: "the player can also perform",
    2127: "\"D-DOWN\" and",
    2128: "\"SPLIT\".",
    2130: "Can only be performed when the player",
    2131: "holds exactly 2 cards.",
    2132: "Double your bet (Double Down).",
    2133: "If your current coins are less than the bet amount,",
    2134: "you cannot perform it.",
    2135: "If you D-DOWN and defeat the dealer,",
    2136: "the payout is doubled (2x).",
    2137: "Can be done when the player's initial 2 cards",
    2138: "have identical ranks (Split).",
    2139: "Split the 2 cards into 2 separate hands",
    2140: "and play each hand individually.",
    2143: "Even after a SPLIT,",
    2144: "you can still D-DOWN",
    2145: "on each hand.",
    2146: "When SPLIT,",
    2147: "getting an Ace and a 10~K",
    2148: "does not count as Blackjack,",
    2149: "but counts as a regular 21.",
    2150: "[About INSURANCE]",
    2151: "It is a kind of insurance policy:",
    2152: "if the dealer's upcard is an Ace,",
    2153: "the dealer will offer Insurance.",
    2154: "If you do not want it,",
    2155: "select NO.",
    2156: "The game will proceed as normal.",
    2157: "Pay half your BET amount",
    2158: "as an insurance premium.",
    2159: "If the dealer's hole card is 10~K",
    2160: "(meaning Blackjack),",
    2161: "your BET is lost, but insurance pays 2:1,",
    2162: "and the hand ends there.",
    2163: "If the dealer's hole card",
    2164: "is A~9,",
    2165: "the insurance premium is lost,",
    2166: "and the game proceeds as normal.",
    2167: "This game uses",
    2168: "4 decks (208 cards),",
    2169: "so the exact same card",
    2170: "may appear 2 or more times.",
    2171: "HIT.",
    2173: "STAND.",
    2176: "D-DOWN.",
    2177: "SPLIT.",
    2178: "(Only when SPLIT is available)",
    2179: "Quit.",
    2181: "Card total is greater than dealer's,",
    2184: "or the dealer busts.",
    2185: "A 2-card combination of an Ace",
    2186: "and any 10~K (Blackjack).",
    2187: "(Automatically STANDs)",
    2188: "When SPLIT, counts as 21.",
    2189: "Reaching 6 cards without busting",
    2191: "and STANDing (6-Card Charlie).",
    2192: "Reaching 7 cards",
    2193: "without exceeding 21 (7-Card Charlie).",
    2194: "Blackjack with Ace and Jack",
    2195: "where both cards share the same suit:",
    2197: "Hearts, Clubs, or Diamonds.",
    2198: "Spades (Ace & Jack of Spades).",
    2199: "Both dealt cards are 7,",
    2202: "and hitting a 3rd card",
    2203: "draws another 7 (Triple Seven).",
    2204: "HIT.",
    2205: "STAND.",

    # Batch 4: IDs 2211 - 2273 (Slot Machine rules)
    2211: "A slot machine composed of",
    2212: "16 small reels.",
    2213: "Depending on the number of coins bet,",
    2214: "the number of active paylines",
    2215: "increases.",
    2216: "You can bet",
    2217: "up to 8 coins.",
    2218: "Bets 3, 4, 7, and 8 activate vertical",
    2219: "paylines.",
    2220: "Each bet activates 2",
    2221: "paylines.",
    2222: "When the game starts,",
    2223: "all reels",
    2224: "begin spinning.",
    2225: "After spinning a certain amount,",
    2226: "the small reels stop first.",
    2227: "(The big reel keeps spinning.)",
    2228: "Press the 〇, ✕, △, ▢ buttons",
    2229: "to shift their positions clockwise.",
    2230: "Skillfully shift the small reels",
    2231: "to align the symbols",
    2232: "and adjust them.",
    2233: "Once finished adjusting the small reels,",
    2234: "press R1 or R2",
    2235: "to stop the big reel.",
    2236: "If 3 or more matching symbols line up",
    2237: "along an active bet line,",
    2238: "you win.",
    2239: "Bets 1~4 can match up to 5 symbols,",
    2240: "while Bets 5~8 can match up to 4 symbols.",
    2241: "each in a row.",
    2242: "If the big reel's symbols align",
    2243: "diagonally, in all 4 corners, or entirely,",
    2244: "regardless of active bet lines,",
    2245: "you win.",
    2246: "For wins on the big reel,",
    2247: "the payout is multiplied by the bet count.",
    2248: "Bet 1 coin.",
    2249: "Rotate the 4 small reels",
    2250: "on the right.",
    2253: "Rotate the 4 small reels on the bottom.",
    2255: "Rotate the 4 small reels on top.",
    2257: "Rotate the 4 small reels on the left.",
    2260: "Stop the big reel.",
    2261: "Quit the slot machine.",
    2262: "Different machines have different symbols",
    2263: "that hit more easily.",
    2264: "Instead of sticking to just one machine,",
    2265: "trying out various machines is recommended.",
    2266: "During play, it's easy to forget to rotate",
    2267: "the small reels, so please pay attention.",
    2268: "Skillfully adjusting the small reels is the secret to increasing your coins.",
    2269: "If you play with small bets,",
    2270: "when the big win comes,",
    2271: "you'll miss out on a massive payout.",
    2272: "It's best to always challenge",
    2273: "with 8 BET (Full Bet).",

    # Batch 5: IDs 2279 - 2336 (Dice Game rules)
    2279: "Two dice appear on screen;",
    2280: "this game has you predict",
    2281: "their total sum.",
    2282: "You can bet on as many spots as you like,",
    2283: "up to a maximum of 100 bets",
    2284: "per spot.",
    2285: "If you bet on the dice total,",
    2286: "you win and receive a payout based on the odds.",
    2287: "You can also challenge the Extra Game by risking your payout.",
    2288: "Rather than \"guessing the exact total,\"",
    2289: "it is a game where",
    2290: "\"any total wins,",
    2291: "as long as 7 doesn't appear.\"",
    2292: "That is how the game works.",
    2293: "(Payouts differ based on",
    2294: "the total value.)",
    2295: "If a 7 rolls, the round ends,",
    2297: "so please be careful.",
    2298: "Bet 10 coins on the spot",
    2299: "indicated by the cursor.",
    2300: "[When a Total Hits]",
    2301: "Challenge Extra Game.",
    2303: "Cancel all coins on the spot",
    2304: "indicated by the cursor.",
    2311: "Bet 100 coins.",
    2315: "Cancel all.",
    2318: "If coins were bet...",
    2322: "Quit Dice Game.",
    2325: "Select betting spot.",
    2328: "Numbers closer to 7",
    2329: "appear with higher probability.",
    2330: "Betting more on numbers close to 7",
    2331: "and less on numbers close to 2 or 12",
    2332: "is a solid strategy.",
    2333: "In the Extra Game,",
    2334: "all earned coins will be forfeited if you lose,",
    2335: "so not getting greedy and quitting at a good point",
    2336: "is the trick to keeping your winnings.",

    # Batch 6: IDs 2337 - 2384 (Codebreaker rules)
    2337: "Current Metal Card count:",
    2342: "Numbers 1~9 are placed in random order.",
    2343: "Guess the correct sequence of the",
    2344: "randomly placed numbers.",
    2345: "You can win",
    2346: "great prizes.",
    2347: "If you fail to answer within the set number of tries, it's Game Over.",
    2348: "Tries equal the number of RESULT slots.",
    2349: "If the entered",
    2350: "answer is incorrect,",
    2351: "it will be recorded sequentially,",
    2352: "so use it as reference for your next guess.",
    2353: "Displayed above the input area,",
    2354: "are indicators:",
    2355: "each number lights up when chosen and turns off when unused; check these lights",
    2356: "to make sure numbers 1~9 are assigned evenly",
    2357: "without any duplicate digits.",
    2358: "Check using this display.",
    2359: "This game uses \"Metal Cards\" instead of coins.",
    2360: "Change the number at the cursor",
    2361: "to a lower value.",
    2362: "Change the color (mark) of the number at the cursor.",
    2363: "Use this as a reminder when you've decided",
    2364: "\"this number is confirmed.\"",
    2366: "Change to a higher value.",
    2371: "Quit Codebreaker.",
    2372: "Move cursor.",
    2373: "The key to this game",
    2374: "is figuring out which positions scored a Hit (H) in both rows.",
    2375: "For spots that hit in both rows,",
    2376: "let's mark them",
    2377: "for now.",
    2378: "The RESULT history of past guesses is also a major hint,",
    2379: "so be sure to reference it.",
    2380: "To think he knows this much",
    2381: "about St. Hermelin...",
    2382: "Quite surprising.",
    2383: "Nanjo: Going to see a doctor...",
    2384: "is something I'd rather avoid, but...",

    # Batch 7: IDs 2385 - 2554 (Town / Hospital / Shrine / Rumors / Banter)
    2385: "Kinda feels like",
    2386: "it's getting to be a pain, don'tcha think?",
    2387: "Going to the hospital, I mean.",
    2388: "Gotta head over to the shrine...",
    2389: "She's an upperclassman of ours, isn't she?",
    2390: "I've heard about her.",
    2392: "Could she be Sonomura's mother?",
    2393: "Don't you think?",
    2394: "Let's head to Araya Shrine.",
    2395: "It's right nearby, after all.",
    2396: "Let's go to the Abandoned Factory.",
    2397: "From a place like that,",
    2398: "can we really get in?",
    2399: "That uniform!",
    2400: "I'm an alumna, you know!",
    2401: "And she's working as a teacher too.",
    2402: "They said she was walking around here earlier.",
    2403: "Was she attacked, I wonder...?",
    2404: "Hello.",
    2405: "Your friend...",
    2406: "is quite an eccentric character, huh.",
    2446: "Haunted mansions and the like...",
    2447: "I have never visited such a place.",
    2448: "I'd love to become like that.",
    2449: "It's an abandoned house, right?",
    2450: "We used to play there on our own.",
    2451: "It's quiet.",
    2452: "It almost feels like",
    2453: "nothing ever happened at all.",
    2454: "I've played at that haunted mansion before!",
    2455: "That creature roaming around...",
    2456: "it's not a bear, right?",
    2457: "Why did they suddenly",
    2458: "start appearing?",
    2459: "When you were a kid,",
    2460: "did you ever go there?",
    2461: "It was a playground",
    2462: "for the kids.",
    2463: "Could it be a raccoon?",
    2464: "Nice weather, isn't it?",
    2465: "Doctor: Even in a big city like this,",
    2466: "do they really appear...?",
    2468: "Doctor: It'll cost 1,000 yen, but...",
    2513: "If only I had this scarf...",
    2515: "Were you asked to do something?",
    2516: "We're going to the hospital!",
    2517: "Such terrible taste!",
    2518: "Maybe just that brown-haired girl I see from time to time.",
    2521: "Where are we heading next?",
    2522: "Anywhere is fine with me.",
    2523: "As long as we reach the hospital.",
    2524: "Surprisingly resilient.",
    2525: "Isn't that...",
    2526: "piano music and singing?",
    2527: "I heard something like that",
    2528: "somewhere before!",
    2529: "Acting like nothing's wrong?!",
    2530: "If you get wiped out,",
    2531: "don't come crying to me!",
    2532: "There was someone who said something similar",
    2533: "just like that.",
    2535: "I wonder what kind of shop that is?",
    2536: "That's enough already.",
    2537: "Shouldn't we head to Araya Shrine?",
    2538: "Welcome! Good to see you.",
    2539: "Take your time and relax.",
    2541: "Must be tough.",
    2542: "In just one building,",
    2543: "there's a strange shop.",
    2544: "It's supposed to be closed,",
    2545: "and nobody's seen anyone go in...",
    2546: "Yet music can be heard playing inside.",
    2547: "Strange things happen, I tell ya.",
    2548: "Old Man: Speaking of that strange shop",
    2549: "in this shopping arcade...",
    2550: "I heard a rumor that it's going to open.",
    2551: "That's what they say.",
    2552: "Though as for when that will be,",
    2553: "I haven't the slightest idea.",
    2554: "...they say.",

    # Batch 8: IDs 2612 - 2647 (Satomi Tadashi / Jingle / Uncle / Agastya Tree)
    2612: "Nanjo: ...Heal your ill~ness...",
    2613: "Dis-Sick...",
    2614: "This song!",
    2615: "It'll brainwash you!",
    2616: "Nanjo: The only thing one can rely on",
    2617: "is one's own strength...",
    2618: "What a hollow philosophy.",
    2619: "Tadashi's...",
    2620: "uncle's shop, huh?",
    2621: "The shop in Mikage Sun Mall",
    2622: "is his family's main store, right?",
    2623: "She's really got her act together.",
    2625: "Makes you wonder.",
    2626: "We made it at last.",
    2628: "might have ended up that way too.",
    2629: "I want to unravel this mystery,",
    2630: "that's what I've been thinking.",
    2631: "Putting what I learned to use...",
    2632: "This is my big chance!",
    2633: "I'll give you a discount!",
    2634: "Demons and monsters...",
    2635: "aren't scary at all!",
    2636: "It's gotta be an optical illusion",
    2637: "or some kind of parlor trick,",
    2638: "no doubt about it!",
    2639: "It grows right there,",
    2640: "why don't you go take a look?",
    2641: "It's my uncle's",
    2642: "private room~",
    2643: "You're not allowed in~",
    2644: "Hiding under the covers,",
    2645: "shivering with fright...",
    2646: "We have to do something",
    2647: "about this ourselves.",

    # Batch 9: IDs 2659 - 2785 (Velvet Room / Igor Tutorials)
    2659: "Grrrgh!",
    2660: "Igor: Welcome.",
    2661: "To the chamber that awakens ancient forms...",
    2662: "Would you care to show me?",
    2664: "Igor: What is your desire?",
    2665: "Is this acceptable?",
    2666: "I cannot store any.",
    2667: "I cannot store any Personas.",
    2668: "Igor: What will you do?",
    2669: "Farewell then...",
    2670: "Igor: If you seek a new Persona,",
    2671: "I shall perform fusion",
    2672: "and create one for you.",
    2673: "In order for me to create a Persona,",
    2674: "demons summoned from the Netherworld",
    2675: "must be fused together.",
    2676: "To summon demons, certain cards are required.",
    2677: "Upon those cards,",
    2678: "the demon's summoning incantation",
    2679: "is inscribed, you see.",
    2680: "They are called Summoning Spell Cards, and each demon carries only one.",
    2681: "They are uniquely possessed by them.",
    2682: "Therefore...",
    2683: "First,",
    2684: "you must collect Spell Cards.",
    2685: "Negotiate with demons and obtain them yourselves.",
    2686: "Even when encountering demons,",
    2687: "fighting is not the only option.",
    2688: "Do you understand?",
    2689: "For they do not always",
    2690: "desire battle...",
    2691: "Igor: In order to wield a newly fused Persona",
    2692: "as your own power,",
    2693: "and demonstrate its full potential...",
    2694: "fusion alone is not enough.",
    2695: "Only by equipping the Persona",
    2696: "to your own soul",
    2697: "can you truly master its abilities.",
    2698: "Each person can equip",
    2699: "up to three Personas at a time.",
    2700: "Newly fused Personas",
    2701: "are kept safely in my custody.",
    2702: "When needed,",
    2703: "please instruct me to equip them.",
    2704: "I can store up to 16 Personas,",
    2705: "so please swap them as needed.",
    2706: "Just as human personalities vary,",
    2707: "Personas come in myriad varieties;",
    2708: "their shapes and inner natures are distinct.",
    2709: "Depending on the situation,",
    2710: "switching between them will be necessary.",
    2711: "And if you can master wielding them,",
    2712: "a splendid Persona user",
    2713: "you shall become.",
    2714: "While you can equip up to 3 Personas,",
    2716: "one Persona is ready to be invoked in battle.",
    2717: "That means calling forth the Persona",
    2718: "during battle.",
    2719: "The remaining two",
    2720: "are in a charged standby state,",
    2721: "and can be switched to Active.",
    2722: "The active Persona",
    2723: "supplements and enhances your various abilities.",
    2724: "It lends you its power.",
    2725: "Without the power of Persona,",
    2726: "you would be no different from ordinary humans,",
    2727: "and possess no special defenses,",
    2728: "and when demons cast magic upon you,",
    2729: "you would lack the strength to endure it.",
    2730: "If struck directly,",
    2731: "you would likely not survive.",
    2732: "However, with a Persona, your magic defense",
    2733: "rises dramatically.",
    2734: "Some will see their Strength increase,",
    2735: "and your Agility or Luck may rise as well.",
    2736: "It all represents",
    2737: "a hidden facet of yourself.",
    2738: "Once equipped,",
    2739: "you would do well to inspect your status.",
    2740: "You will see clearly",
    2741: "how you have transformed.",
    2742: "At first, no one",
    2743: "can unleash the full potential",
    2744: "of their Persona.",
    2745: "The more you invoke it in battle, the more power you can draw out.",
    2746: "The attack methods available",
    2747: "in battle will increase.",
    2748: "Even as attack methods expand",
    2749: "and you choose more powerful attacks,",
    2750: "the SP required for invocation remains unchanged.",
    2751: "Through battle, remember that",
    2752: "both you and your Personas",
    2753: "are continuously growing...",
    2754: "Igor: This is just",
    2755: "a bit of meddling advice from me, but...",
    2756: "Persona growth consists of 8 ranks,",
    2757: "so I recommend occasionally raising one to its limit.",
    2758: "I strongly encourage it.",
    2760: "I believe good things may come of it...",
    2761: "In fusion,",
    2762: "various factors are involved,",
    2763: "from subtle nuances to major elements:",
    2764: "even when fusing the same Persona,",
    2765: "what combination of Spell Cards was used...",
    2766: "which demons were combined...",
    2767: "the affinity based on the demon tribes...",
    2768: "their elemental compatibility...",
    2769: "the positions of Terra and Luna (the moon) at fusion...",
    2770: "or whether another essence was added...",
    2771: "I forgot to mention...",
    2772: "by adding an item as well,",
    2773: "into the fusion,",
    2774: "it is possible to induce further alterations.",
    2775: "Depending on the item,",
    2776: "there are times when the outcome can be predicted,",
    2777: "well in advance,",
    2778: "but at other times, even I",
    2779: "cannot foresee the result.",
    2780: "In such cases, please forgive me.",
    2781: "It is well worth experimenting with...",
    2782: "It has the effect of altering the tier within the resulting tribe",
    2783: "created from the fusion.",
    2784: "I recommend trying it",
    2785: "for yourself.",

    # Batch 10: IDs 2798 - 2809 (Yuko Himeno's House)
    2798: "Cozy little house, huh.",
    2799: "Compared to your mansion,",
    2800: "everywhere looks cozy, don't it?!",
    2801: "Sheesh...",
    2802: "Rich boys...",
    2803: "This is Yuko Himeno's house. Sonomura's friend...",
    2804: "Since she's doing that...",
    2805: "Mark: Urrgh...",
    2806: "That's enough to bring a tear to my eye!",
    2807: "Work a part-time job",
    2808: "and pay for it yourself!",
    2809: "Looks like she isn't back yet.",
}

def main():
    chunk_path = Path("scripts/retranslate/chunks/E2_part_02.json")
    with open(chunk_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    entries = data["entries"]
    print(f"Loaded {len(entries)} entries from {chunk_path}")

    missing = []
    for e in entries:
        eid = e["id"]
        if eid in translations:
            e["translation_en"] = translations[eid]
        else:
            missing.append((eid, e["text_jp"]))

    if missing:
        print(f"[!] Missing {len(missing)} translations:")
        for eid, jp in missing[:15]:
            print(f"  ID {eid}: {jp}")
        return

    # Check for empty / placeholder translations
    empty_count = sum(1 for e in entries if not e.get("translation_en", "").strip())
    print(f"Empty count: {empty_count}")

    with open(chunk_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    print(f"[+] Successfully wrote {len(entries)} translations to {chunk_path}")

if __name__ == "__main__":
    main()
