#!/usr/bin/env python3
"""
Translation builder for scripts/retranslate3/chunks/E2_part_03.json (IDs 724..1085)
"""
import json
from pathlib import Path

CHUNK_PATH = Path(__file__).resolve().parent / "chunks" / "E2_part_03.json"

t_map = {}

# --- IDs 724..749: Alternate School, Gymnasium, Demonic Rumors ---
t_map[724] = "...as long as we resolve it ourselves, everything will be fine."
t_map[725] = "Elly: Even if someone looks as cute as an angel on the outside,"
t_map[726] = "it doesn't necessarily mean they're like that on the inside."
t_map[727] = "That's how it is, you see."
t_map[728] = "Brown: Everywhere we go,"
t_map[729] = "it's always demons this, demons that~"
t_map[730] = "Ain't there anything more fun to talk about?"
t_map[731] = "If any kid gets out of hand, this big bro will give 'em a spanking!"
t_map[732] = "Ayase: This school is kinda weird."
t_map[733] = "It's got this strangely fake vibe to it."
t_map[734] = "Ayase: Yeah, I knew it. This place..."
t_map[735] = "...is totally different from our school, no wonder it felt totally fake!"
t_map[736] = "...taking it easy without even knowing what's happening around them."
t_map[737] = "Student: Why is that girl in black..."
t_map[738] = "...targeting this school?"
t_map[739] = "Does she have some kind of grudge against us?"
t_map[740] = "Student: Nothing's gonna surprise me anymore!"
t_map[741] = "Like, for instance, even if I heard that you..."
t_map[742] = "...can actually control demons or whatever!"
t_map[743] = "...Haha, as if~!"
t_map[744] = "There's no way that's true, right~?"
t_map[745] = "...Wait, doesn't she look like someone?"
t_map[746] = "Student: Oh, I just remembered!"
t_map[747] = "I've met a girl dressed in white before."
t_map[748] = "I met her once around here."
t_map[749] = "Though I guess that has nothing to do with this, right?"

# --- IDs 750..779: Gymnasium Ballet Club, Peeping Accusation ---
t_map[750] = "Brown: Man, what a total pain..."
t_map[751] = "Maki: Does your school's gymnasium..."
t_map[752] = "...have club rooms and stuff too?"
t_map[753] = "Nanjo: Truly antiquated."
t_map[754] = "I wouldn't be surprised in the least..."
t_map[755] = "...if it collapsed at any moment."
t_map[756] = "Mark: The curtain's full of holes..."
t_map[757] = "I'm not peeping, alright?!"
t_map[758] = "Elly: The more I look at this town, the more mysterious it seems."
t_map[759] = "It really feels like a world from the past."
t_map[760] = "Brown: Tch, so cramped and narrow."
t_map[761] = "They should just tear this place down..."
t_map[762] = "...and rebuild it already!"
t_map[763] = "Ayase: Ayase's never been..."
t_map[764] = "...to a place like this before."
t_map[765] = "Reiji: I'm not here to keep you company on your little stroll."
t_map[766] = "Student: Ah! You... don't tell me..."
t_map[767] = "...you came here to peep on us?!"
t_map[768] = "Mark: D-Don't be ridiculous!"
t_map[769] = "Who'd wanna peep on you girls, anyway...?"
t_map[770] = "We want a club room for the ballet club!"
t_map[771] = "If we had a club room, we could change clothes..."
t_map[772] = "...without worrying about peeping toms!"
t_map[773] = "Elly: ...It's useless, Mark. Come, let us go."
t_map[774] = "There's no point trying to explain it to them!"
t_map[775] = "Come on, let's get going!"
t_map[776] = "Maybe your everyday behavior is just too shady?"
t_map[777] = "Come on, we're leaving already!"
t_map[778] = "Nanjo: Stop dwelling on trivial nonsense, Inaba!"
t_map[779] = "Now, let us move."

# --- IDs 780..813: Girl in Black, Himeno Taken, Forest Mystery ---
t_map[780] = "Student: Ah... That's the girl!"
t_map[781] = "She's the one who took Himeno-san away! Looked like she had demons with her, too!"
t_map[782] = "Are we just supposed to stay here and wait to get attacked?!"
t_map[783] = "Leave it to us! Don't worry!"
t_map[784] = "Let's hurry and get going!"
t_map[785] = "Student: I've actually met a girl who looked just like that girl in black before."
t_map[786] = "Nanjo: You're saying there is another girl?"
t_map[787] = "Student: Yeah, pretty sure."
t_map[788] = "...It's a forest now, but..."
t_map[789] = "...you know that place that was a flower garden until recently?"
t_map[790] = "You know that spot, right?"
t_map[791] = "I saw her playing over there."
t_map[792] = "Mark: Uh, wait, a flower garden?"
t_map[793] = "Man... this town makes zero sense."
t_map[794] = "Elly: Are you talking about what Naito-kun said, about the police station turning into a forest?"
t_map[795] = "Ayase: A forest? Is that the thing Naito was talking about?"
t_map[796] = "...Saying the police station turned into a forest?"
t_map[797] = "Brown: Speaking of forests, Naito was saying something about that, wasn't he?"
t_map[798] = "...He said something about that."
t_map[799] = "...Like how the police station became a forest."
t_map[800] = "Nanjo: Come to think of it..."
t_map[801] = "...Naito did mention that where the police station used to be..."
t_map[802] = "...turned into a forest."
t_map[803] = "Maki: The police station...?"
t_map[804] = "...That's where we went to rescue Inaba-kun and Uesugi-kun, right?"
t_map[805] = "Now that you mention it, that's definitely that area..."
t_map[806] = "It used to be a pretty flower garden,"
t_map[807] = "but then it suddenly turned into a huge forest,"
t_map[808] = "so I was really surprised too."
t_map[809] = "Student: What are you all muttering about among yourselves?"
t_map[810] = "Hey, you guys are acting pretty suspicious."
t_map[811] = "Hey, are you guys really students here?"
t_map[812] = "Maki: Hey everyone, we've gotta hurry! Well then, we have to go now, so see you later!"
t_map[813] = "We're going now, bye!"

# --- IDs 814..835: School Search, Infirmary & Teachers ---
t_map[814] = "Ayase: Are there demons in here too...?"
t_map[815] = "Maki: Let's hurry and look for her! She's gotta be somewhere in the school!"
t_map[816] = "Nanjo: Why is that girl in black..."
t_map[817] = "...targeting the school...?"
t_map[818] = "What does she hope to accomplish..."
t_map[819] = "...by attacking a school?"
t_map[820] = "Mark: When are we gonna be able to rescue the real Maki, anyway...?"
t_map[821] = "Elly: As I thought, she must be leading Demons with her."
t_map[822] = "If so, we must brace ourselves and proceed with caution."
t_map[823] = "Leaving two women behind here..."
t_map[824] = "...worried about leaving them alone?"
t_map[825] = "Brown: If you want, the great Brown here..."
t_map[826] = "...can stay and protect the teachers!"
t_map[827] = "Ayase: Finding an infirmary in a place like this..."
t_map[828] = "...really puts me at ease."
t_map[829] = "Reiji: What's with that dark classroom?"
t_map[830] = "What's happening right now?"
t_map[831] = "Even the teachers don't know what to do..."
t_map[832] = "Yukino: Hey, Ms. Saeko?"
t_map[833] = "Ms. Saeko: It really is dark, isn't it..."
t_map[834] = "Ms. Hishimi: If you get hurt, I'll take a look at you."
t_map[835] = "Nurse: That really surprised me earlier! Thank you!"

# --- IDs 836..865: Himeno's Residence (Alternate Rich Himeno) ---
t_map[836] = "Himeno: Oh my, what business do you all have here?"
t_map[837] = "Did you come to see the treasures in our storehouse?"
t_map[838] = "I'm sorry, but we have strict anti-theft security,"
t_map[839] = "Mark: Anti-theft? Are you saying you suspect us?!"
t_map[840] = "Himeno: My, is that how it sounded to you?"
t_map[841] = "Goodness, aren't you touchy and jealous!"
t_map[842] = "I certainly didn't mean it that way..."
t_map[843] = "I'm feeling a bit indisposed."
t_map[844] = "Would you mind stepping outside ahead of me?"
t_map[845] = "Brown: Gaaah! She really pisses me off!"
t_map[846] = "Ayase: Himeno was way cuter before!"
t_map[847] = "Reiji: I'm heading outside."
t_map[848] = "Maki: Yuko, that's rude to everyone! Apologize!"
t_map[849] = "Himeno: Maki is my friend, but..."
t_map[850] = "...none of the others are!"
t_map[851] = "Maki: Oh, Yuko... Geez, what am I going to do with you..."
t_map[852] = "Maki: Well everyone,"
t_map[853] = "...let's get going."
t_map[854] = "Himeno: Maki, would you like to have tea at my place?"
t_map[855] = "I have just one serving of pastries left from our pastry chef."
t_map[856] = "Maki: If you do that, the others will be pleased too!"
t_map[857] = "Then let's all drop by together next time!"
t_map[858] = "Himeno: Hmph, how boring!"
t_map[859] = "...Fine, today I'll make a special exception..."
t_map[860] = "...and invite everyone in!"
t_map[861] = "Himeno: N-No, that's not it at all!"
t_map[862] = "We have a Doberman named John,"
t_map[863] = "and Sebastian the butler! I'm not scared in the least!"
t_map[864] = "Nanjo: Hmph. Then once this is all resolved,"
t_map[865] = "...we shall all pay you a visit afterward."

# --- IDs 866..903: Mrs. Kaneda's Residence (Ruin Excavator) ---
t_map[866] = "Mrs. Kaneda: What business do you have with my place?"
t_map[867] = "Don't tell me you're debt collectors..."
t_map[868] = "...As you can see, I ain't got a dime here!"
t_map[869] = "There ain't no money in this house!"
t_map[870] = "There were no treasures in the ruins I was counting on,"
t_map[871] = "so business is totally dead!"
t_map[872] = "Nanjo: She suddenly became wealthy recently..."
t_map[873] = "...and is doing business with ruins?"
t_map[874] = "Maki: Nanjo-kun, stop! Mrs. Kaneda's job is grave robbing ruins, isn't it?!"
t_map[875] = "Elly: 'Grave robbing'? That can hardly..."
t_map[876] = "...be called a legitimate job!"
t_map[877] = "Besides, in modern-day Japan, how could anyone do something like that?"
t_map[878] = "Maki really says the strangest things..."
t_map[879] = "Brown: Grave robbing? Ain't no way you can pull that off in Japan!"
t_map[880] = "Maki-chan says some weird things, man."
t_map[881] = "Ayase: Grave robbiiing~?"
t_map[882] = "There's no way anyone does that for a living~!"
t_map[883] = "...No way in the world!"
t_map[884] = "Ayase: Maki, get it together~!"
t_map[885] = "Maki: But..."
t_map[886] = "...everyone's saying that, isn't that right?"
t_map[887] = "Mark: Come to think of it,"
t_map[888] = "...there was a rumor about a year ago that the old lady got rich quick by looting ruins..."
t_map[889] = "...About a year ago, there was a rumor like that~"
t_map[890] = "...Though you're a different Maki from this world, so..."
t_map[891] = "Mrs. Kaneda: Quit your blabbering! If you don't have any business here..."
t_map[892] = "Mrs. Kaneda: You're still here?!"
t_map[893] = "If you've got no business, hurry up and get out!"
t_map[894] = "Nanjo: Maki said that old lady Kaneda makes her living from grave robbing."
t_map[895] = "In our town, that was nothing more than a mere rumor."
t_map[896] = "Yet in this town, it appears to have become reality."
t_map[897] = "Why has a rumor become reality?"
t_map[898] = "Brown: Ugh, my stomach hurts..."
t_map[899] = "Hey everyone, let's get going already!"
t_map[900] = "Suddenly everywhere in this town..."
t_map[901] = "...has gone completely wild and ruined!"
t_map[902] = "You guys are strong, aren't you? Looking at this state of affairs,"
t_map[903] = "...don't you feel like doing something about it?!"

# --- IDs 904..932: Joy Street & Shopping District, Weapons & Magazines ---
t_map[904] = "Mark: Sorry, Granny."
t_map[905] = "We're in a rush ourselves, you see."
t_map[906] = "Elly: Mark, calm down... I'm sure Maki will be fine."
t_map[907] = "Come, let us go search for her quickly!"
t_map[908] = "Maki will surely be fine. Let us make haste and search for her."
t_map[909] = "It'll be fine! In just a little while,"
t_map[910] = "...everything will be resolved."
t_map[911] = "It's alright. Very soon,"
t_map[912] = "...everything should be resolved."
t_map[913] = "Brown: Whoa whoa, Mark, don't get so heated!"
t_map[914] = "...The great Brown here will take care of everything in no time!"
t_map[915] = "Just a little longer, and everyone will be back to normal!"
t_map[916] = "Reiji: Calm down, Inaba."
t_map[917] = "...Then I'll blow 'em all away."
t_map[918] = "Welcome to the boutique!★"
t_map[919] = "Brown: Sheesh, what a drag..."
t_map[920] = "Nanjo: In this town, weapons..."
t_map[921] = "...are entirely intended for dealing with demons."
t_map[922] = "Which explains why there's no need for the police either."
t_map[923] = "Mark: No matter how many times I come here, I can't get used to someone smiling warmly and asking, 'Looking for weapons?'"
t_map[924] = "Elly: The magazines placed here are all old, aren't they?"
t_map[925] = "Elly: All the magazines here are old."
t_map[926] = "Brown: This girl already retired, though..."
t_map[927] = "Why is she on the front cover?"
t_map[928] = "Ayase: Gross! Look at this!"
t_map[929] = "...Look at this model! Wearing clothes like this..."
t_map[930] = "...no one dresses like this anymore..."
t_map[931] = "Huh? This magazine's old! It's from a whole year ago!"
t_map[932] = "Reiji: What is this shop? They only stock absurdly old magazines."

# --- IDs 933..970: Boutique, Mannequin, Daikanyama vs Shibuya ---
t_map[933] = "Youth: That place that used to be a pretty..."
t_map[934] = "...flower bed suddenly turned into a forest."
t_map[935] = "Are they running some kind of greening campaign right now?"
t_map[936] = "Townsperson: A little girl used to play in that flower bed often."
t_map[937] = "Yet now that it's turned into a forest,"
t_map[938] = "I wonder what became of that child..."
t_map[939] = "Yeah, that girl was a cute little one dressed in white."
t_map[940] = "...dressed in white clothes, she was very cute."
t_map[941] = "Clerk: Are you looking for weapons?"
t_map[942] = "Clerk: That area is for employees only!"
t_map[943] = "Clerk: If you're here to shop, please step up to the counter!"
t_map[944] = "People say being too happy makes them uneasy..."
t_map[945] = "Having fun every day is the best, don't you think?"
t_map[946] = "Nanjo: I won't ask for luxury, but a shirt with the '#1' mark on it..."
t_map[947] = "Nanjo: ...My apologies."
t_map[948] = "Mark: My mom's fashion sense is the absolute worst!"
t_map[949] = "Last time she bought me a T-shirt with 'Air-Raid Shelter' written across the chest!"
t_map[950] = "...bought me a T-shirt with that printed on it!"
t_map[951] = "Where on earth does she even find that kind of stuff?!"
t_map[952] = "...Don't get me wrong, I don't hate my mom or anything!"
t_map[953] = "Elly: I don't particularly care for protective armor."
t_map[954] = "Brown: Hey, pick something that looks cool for the great Brown, even if its defense is low!"
t_map[955] = "...pick a badass one for me!"
t_map[956] = "Ayase: Ayase wants a miniskirt! If the length is too long, wouldn't that look so unfashionable?"
t_map[957] = "Townsperson: Living in such a nice town makes me so happy."
t_map[958] = "Though when people get too happy, they actually start feeling uneasy."
t_map[959] = "I keep wondering if I'll wake up tomorrow and find out this was all just a dream."
t_map[960] = "Mannequin: Welcome~! Looking for anything in particular, honey?"
t_map[961] = "I can check your size if you'd like!"
t_map[962] = "Maki: I've heard of Shibuya,"
t_map[963] = "but what's Daikanyama?"
t_map[964] = "Is that a place name?"
t_map[965] = "In your world, there are places like that too..."
t_map[966] = "...Huh, interesting..."
t_map[967] = "Nanjo: Do you believe that..."
t_map[968] = "...as long as every day is fun, that is enough?"
t_map[969] = "Even if something ominous is brewing behind the scenes..."
t_map[970] = "...is it truly better to fool around in blissful ignorance?"

# --- IDs 971..1006: High School Girls, Subway, Demons Spreading ---
t_map[971] = "Mark: Compared to Shibuya, Daikanyama is a pretty small town,"
t_map[972] = "...compared to Shibuya,"
t_map[973] = "but magazines have been doing a lot of features on it lately..."
t_map[974] = "...so you'd think these girls would know about it."
t_map[975] = "Elly: We cannot simply spend every day doing only pleasant things."
t_map[976] = "There are times when one must endure hardship, wouldn't you say?"
t_map[977] = "Brown: For the great Brown, having fun surrounded by cute girls is way better!"
t_map[978] = "Yeah, like, say..."
t_map[979] = "Ayase: Ayase wants to do fun things all the time too~"
t_map[980] = "...I just wanna hurry and beat Kandori and go back to being an ordinary girl!"
t_map[981] = "...Hurry up and take down Kandori..."
t_map[982] = "Reiji: Are these guys idiots?"
t_map[983] = "There's no way life is all fun and games, morons!"
t_map[984] = "High School Girl: We used to be able to go across the subway line to hang out,"
t_map[985] = "Nobody pays subway fares anyway so that's fine, but our hangouts have decreased and it's so boring~"
t_map[986] = "...It's really lonely having fewer places to play."
t_map[987] = "So I thought about going over to the other side to play..."
t_map[988] = "...but something's really weird!"
t_map[989] = "I got scared, so I turned right around..."
t_map[990] = "...just before the shopping mall!"
t_map[991] = "Wh-What could have happened over there?"
t_map[992] = "High School Girl: I want to move out soon and live by myself!"
t_map[993] = "Near the plasma tower would be great, since the night view is gorgeous!"
t_map[994] = "Mark: Don't you ever feel like living in Shibuya or Daikanyama?"
t_map[995] = "Girl: What's that? Never heard of 'em."
t_map[996] = "Well, whatever! I love this town anyway."
t_map[997] = "Woman: Every day here is fantastic and fun,"
t_map[998] = "...if only demons didn't show up~"
t_map[999] = "There's been a sudden surge of them lately."
t_map[1000] = "Maki: The demons in town only suddenly increased very recently."
t_map[1001] = "Even though they increased, I haven't heard much..."
t_map[1002] = "...about people actually getting attacked."
t_map[1003] = "Nanjo: However, we have in fact..."
t_map[1004] = "...seen demons attacking people. Could it be that demons are selectively choosing their victims?"
t_map[1005] = "...No, that can't be..."
t_map[1006] = "Mark: Stop making such gloomy faces all the time, let's keep things cheerful!"

# --- IDs 1007..1044: Diner, Shrine Rumors, Devil-banishing Mirror ---
t_map[1007] = "Elly: My skin has been breaking out lately... Battles have been quite harsh, after all."
t_map[1008] = "...Battles have been quite Hard, after all."
t_map[1009] = "Brown: Man, I can't shake off my fatigue lately... Guess none of us can beat father time!"
t_map[1010] = "...Guess even we can't beat our age, huh?"
t_map[1011] = "Ayase: N-No way!"
t_map[1012] = "...Rattle Drink is made from viper snake?!"
t_map[1013] = "Ayase drank that stuff~?!"
t_map[1014] = "Reiji: No, I'm not particularly tired."
t_map[1015] = "Townsperson: Until recently, demons only attacked when that girl in black showed up..."
t_map[1016] = "...but now they show up even when she isn't around,"
t_map[1017] = "...so I'm really worried."
t_map[1018] = "Townsperson: Everyone is terrified of the demons,"
t_map[1019] = "...but there's no need to worry."
t_map[1020] = "I'm sure we won't be attacked."
t_map[1021] = "Shopkeeper: You guys know my idiot son?"
t_map[1022] = "Ever since a cute girl transferred into his class,"
t_map[1023] = "...he's been in a foul mood and won't say a word to me!"
t_map[1024] = "Shopkeeper: Oh, a lie? Sure, sure."
t_map[1025] = "Shopkeeper: Whoops! If you open that door, a demon will jump out at you!"
t_map[1026] = "Ha-ha! You fell for it!"
t_map[1027] = "...Nobody pays fare anyway so that's fine, but our hangouts are gone!"
t_map[1028] = "Maki: We're going to the forest, right? I wonder what that key could possibly be?"
t_map[1029] = "Maki: Let's hurry back to that castle!"
t_map[1030] = "Nanjo: Rushing will not help us."
t_map[1031] = "Taking things one step at a time with certainty is ultimately the fastest path."
t_map[1032] = "Nanjo: Now that we have the Devil-banishing Mirror in hand,"
t_map[1033] = "...reluctant though I am, shall we head to the subway?"
t_map[1034] = "Mark: No burgers, no fries, no chicken, no shakes... What a rip-off!"
t_map[1035] = "...No chicken, no shakes either? This sucks!"
t_map[1036] = "You've got nothing to sell, yet the clerk's acting all high and mighty!"
t_map[1037] = "Mark: Can't really trust that shady old guy,"
t_map[1038] = "...can't really trust him, but..."
t_map[1039] = "...wanna look around for that 'Devil-banishing Mirror' just in case?"
t_map[1040] = "Elly: I never used to take detours before,"
t_map[1041] = "...I never really used to,"
t_map[1042] = "...but doing this is surprisingly fun!"
t_map[1043] = "Elly: Let us head to the shrine! I am very curious to see who awaits us there!"
t_map[1044] = "I am very curious indeed!"

# --- IDs 1045..1085: Diner, Mask, Nazca Geoglyph & Weapons ---
t_map[1045] = "Brown: A diner with no food? How does that even work?! Wahaha!"
t_map[1046] = "Damn it, I'm so starved~!"
t_map[1047] = "Brown: Guess it's about time we head over to the shrine!"
t_map[1048] = "Ayase: Let's go to the shrine~"
t_map[1049] = "...Ayase wants some candy apples~"
t_map[1050] = "Reiji: Staying in this place makes my whole body start itching."
t_map[1051] = "Reiji: Aren't we going to the shrine?"
t_map[1052] = "...That guy didn't seem to be lying."
t_map[1053] = "Clerk: We ain't got food!"
t_map[1054] = "But if you take a breather here,"
t_map[1055] = "...your friend's mind'll clear right up,"
t_map[1056] = "...and they're guaranteed to recall their next objective!"
t_map[1057] = "Townsperson: Yesterday I ran right into a demon,"
t_map[1058] = "...it stared intently right into my face,"
t_map[1059] = "Townsperson: You guys seem somewhat..."
t_map[1060] = "...different from the rest of us. Can't put my finger on it, though..."
t_map[1061] = "Townsperson: You're a really good person. I can tell."
t_map[1062] = "I'm sure your friends think so too."
t_map[1063] = "Townsperson: You're actually doing bad things behind everyone's back, aren't you?"
t_map[1064] = "Don't forget that people are getting hurt because of that!"
t_map[1065] = "...Don't you ever forget that!"
t_map[1066] = "Maki: That mask is so cute!"
t_map[1067] = "I want to decorate my room with it."
t_map[1068] = "Nanjo: Don't get tricked into buying suspicious junk!"
t_map[1069] = "Mark: The relationship between those two really makes me wonder these days..."
t_map[1070] = "Elly: This is a figurine said to bring good fortune in Japan, right?"
t_map[1071] = "Brown: Is this a fox? A beckoning fox?"
t_map[1072] = "...Feels like something's off~"
t_map[1073] = "Ayase: Ayase wants this!"
t_map[1074] = "Hey~, buy it for me!"
t_map[1075] = "Reiji: If the clerk is suspicious, even the ornaments look suspicious."
t_map[1076] = "Townsperson: Demons have increased lately. But they feel different from the demons that girl in black was leading around before."
t_map[1077] = "Reiji: Tch, trying to be funny, huh..."
t_map[1078] = "Brown: Man, what a total drag..."
t_map[1079] = "Nanjo: Will the day ever come when convenience stores sell weapons in our town as well?"
t_map[1080] = "Mark: Tch, nothing but weapons?"
t_map[1081] = "Without a book corner, it feels kind of lonely."
t_map[1082] = "Elly: I wonder what could have happened?"
t_map[1083] = "Brown: Check out this picture!"
t_map[1084] = "...Wait, is this the real deal?!"
t_map[1085] = "Reiji: It looks remarkably like the Nazca geoglyphs."

def build():
    with open(CHUNK_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    entries = data["entries"]
    assert len(entries) == 362, f"Expected 362 entries, got {len(entries)}"

    for e in entries:
        eid = e["id"]
        assert eid in t_map, f"Missing translation for id {eid}"
        e["translation_en"] = t_map[eid]

    with open(CHUNK_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Successfully updated {CHUNK_PATH} with {len(entries)} translations.")

if __name__ == "__main__":
    build()
