#!/usr/bin/env python3
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
TARGET_FILE = BASE_DIR / "chunks" / "E0_part_03.json"

translations = [
    # 0..49 (IDs 928..977)
    "Ayase: What the heck?! Stingy jerk!",
    "Everyone is making fun of Ayase! Fine, drop dead, you jerks!",
    "Let's split up and search for the entrance!",
    "Go hide somewhere!",
    "Maki: I understand already!",
    "Everyone alright with that?",
    "Mark: Tch, no choice then.",
    "Nanjo: Now then, somewhere around here...",
    "I drew this with spray paint. It's called \"graffiti art\"!",
    "It's the shout of my soul, y'know!",
    "Maki: This town, and everyone in it...",
    "Huh? Wh-What?",
    "Doesn't look like it's this way.",
    "If anything happens, let me know right away! I'm the leader, after all!",
    "Maki: ...It's kind of tragic.",
    "Nanjo: Kandori... For the first time,",
    "I see you are this audacious.",
    "Ah, Ayase is...",
    "I'm coming along with you, okay?",
    "You're super lucky, y'know! Got it?",
    "What on earth happened to school? What about Yuko and the others?",
    "Discovered a device!",
    "Did you find something?",
    "Try using it right away!",
    "Here, let me see that.",
    "Maki's Voice: Wh-What?",
    "Beyond here, trusting something whose true nature we don't know...",
    "Ah, sorry. It's nothing.",
    "More importantly, we gotta hurry and chase after him!",
    "I really liked this place, though...",
    "Nanjo: With this lineup,",
    "the road ahead looks grim. Good grief.",
    "Elly: Actually, for some time now,",
    "I have been interested in SEBEC. I am eager to see what lies inside!",
    "The enemy is inside SEBEC.",
    "That is what I believe, at least...",
    "Brown: Al-Alright!",
    "Kandori didn't escape outside, did he?",
    "I really gotta step up right now!",
    "So with that, I leave the front lines to you!",
    "Maybe we shouldn't do this after all?",
    "Ayase: Ah, are we going back?!",
    "Eeh?! We're not?!",
    "There seems to be no further need to use the \"Security Card\".",
    "Children again, you say?",
    "Kandori: How rude, Takeda.",
    "Nanjo: Unchanged as ever, Kandori.",
    "That old man knows nothing.",
    "More importantly, this simply will not do.",
    "Acting like sneak thieves... Your mother will spank your rear ends.",
    # 50..99 (IDs 978..1027)
    "Or perhaps that senile butler of yours?",
    "You... I will never forgive you!",
    "You're gonna pay for this!",
    "Maki: This guy is... Kandori...?",
    "A true heel's gotta act the part!",
    "Ayase: Hey, old man! Don't go treating us like little kids!",
    "What're you rolling those little balls around for, anyway?!",
    "Ill-mannered brats...",
    "Takeda, feel free to kill them. Dispose of them. Just don't ruin the room.",
    "Nanjo: There are no signs he left through the door. There must be another exit somewhere.",
    "Maki: ...That was Kandori...",
    "Have I... somewhere before...?",
    "Elly: Is something the matter, Maki? You look rather pale.",
    "What's wrong, Maki-chan?",
    "Ayase: What's the matter, Sonomura?",
    "What's wrong, Sonomura?",
    "Maki: Huh? N-No...",
    "I'm okay, it's nothing.",
    "Come on, we have to hurry and catch up to him!",
    "Nanjo: There must be another exit. I will keep watch on the outside.",
    "Mark: Still, those guys...",
    "using Personas too caught me off guard!",
    "Maki: Really, it's nothing.",
    "I just got a little dizzy. Thanks for worrying about me, and sorry.",
    "Elly: Kandori's Persona... The Faceless God... The Crawling Chaos...",
    "An aberrant evil god bearing countless names...",
    "The very incarnation of malice, as it were.",
    "Nobody told me those guys were Persona users too~!",
    "There is a switch. Will you press it?",
    "She really is fond of cheap tricks.",
    "Let's hurry and chase him down!",
    "Check if there are any injuries or anything!",
    "If you are ready, let us depart.",
    "Ayase: So we're really going?",
    "Ugh~ Fine, I get it!",
    "He's the one who messed everything up...",
    "I'll never forgive him!",
    "Huh...? Ahaha, it's nothing.",
    "Come on, let's go!",
    "There is no longer any need to press the switch.",
    "The ones who must atone are all of foolish mankind. I am merely their vanguard guide.",
    "Soon, the iron hammer of judgment shall fall.",
    "Nanjo: This is the end of the line for you, Kandori!",
    "Kandori: I knew you would come, boy.",
    "That woman proved unexpectedly disappointing.",
    "Give up and surrender yourself quietly!",
    "Do it now and maybe you'll get off with just life imprisonment!",
    "Ayase: Ayase's super busy, so I ain't wasting time on an old geezer forever!",
    "Kandori: Heh. You certainly know how to bark.",
    "Unfortunately, I have no time to entertain you children.",
    # 100..149 (IDs 1028..1077)
    "There is something I must accomplish.",
    "Kandori, what are you planning?!",
    "Why... do I...?",
    "Brown: Uwaaaaaaagh! Wh-What is that?!",
    "Wh-What is this~?!",
    "Maki: Eeek?! What's happening?!",
    "Y-You tricked usssss!!",
    "The old man doesn't have to die for scum like Kandori!",
    "We came here to beat that bastard down with our own hands, didn't we?!",
    "Nanjo: Wait! That old man...",
    "Besides, we don't even know how to stop it!",
    "Brown: Y-Yeah, exactly!",
    "We gotta listen to the old guy! If we don't hurry, we're done for!",
    "We haven't time to argue!",
    "Let us save him quickly!",
    "Ah, do something!",
    "This! We can stop it with this machine!",
    "We can save him with the red button!",
    "Nanjo: Sonomura? How do you...",
    "Because I just know!",
    "Idiot! Hurry!",
    "Grow up already.",
    "I must take responsibility in this manner...",
    "Once you're dead, it's all over! Even though there could be good things ahead!",
    "Seeing any more people die is just...",
    "We just have to capture Kandori!",
    "Kandori's Voice: Uoooooooh! H-Hurry and stop it!",
    "Maki: N-No way!",
    "Brown: Wh-What the...",
    "Ayase: H-Hold on a second~!",
    "What on earth did you just do?!",
    "Wh-What is this?!",
    "What's this?! My body is reverting!",
    "Are you calling me?!",
    "Let's go, Papa!",
    "Kandori's Voice: Fheheh... Hahaha! I will not die! Now, guide me to your world!!",
    "Wh-What was that?!",
    "Dr. Nikolai: ...the DEVA System...",
    "Mark: ...Oww...",
    "Maki: ...Ugh... mmm...",
    "M-My head...",
    "Brown: A-Alright!",
    "Looks like everyone is unharmed.",
    "You guys really have stubborn luck.",
    "This is our school gym, isn't it? And the one from three years ago...",
    "Brown: ...Hey, hey, isn't this...",
    "And it's the one from three years ago...",
    "Ayase: ...Hey, hey, isn't this...",
    "isn't this Ayase's school gym? Three years ago, right? When they tore it down...",
    "Pull yourself together, Sonomura.",
    # 150..199 (IDs 1078..1127)
    "This is quite different from what your mother said.",
    "Is Mama really not here?",
    "Could what Yosuke-kun said... really be true...?",
    "Student: Ah! There you are!",
    "Naito-kun was badly injured!",
    "That girl in black came again, and...",
    "Maki: No way! Th-That can't be!",
    "Could that be about Yosuke Naito-kun?",
    "If I recall, since about two months ago...",
    "Definitely two months ago, with his girlfriend Matsudaira...",
    "Let's go after Sonomura!",
    "Sonomura's behavior... for someone with amnesia, it's...",
    "Is this really three years ago...? That girl clearly came calling for Sonomura. But...",
    "Three years ago, Sonomura was hospitalized too.",
    "I see...",
    "I feel that something is amiss.",
    "Brown: Still, this place...",
    "Don't you think it's somewhere totally different~?",
    "That's it! It's a dream, a dream! Wahaha!",
    "Ayase: Is \"time-slip\" like, some new sex industry service or something~?",
    "Is that trendy now?",
    "Is Ayase falling behind the times?",
    "Must be nice~ Such a well-matched couple.",
    "Nanjo: Hey, woman over there.",
    "How many days left until the Sports Festival?",
    "There's still a month left until the Sports Festival, silly.",
    "Hey, what year am I in?",
    "Aren't you all second-years?",
    "It looked like you guys just appeared out of thin air, but...",
    "that's just my imagination, right? Ahahahaha!",
    "Mark: ...Hey, this place is...",
    "Naito... You mean that guy who went missing two months ago?",
    "I never thought I'd meet people from our original world again!",
    "No way... You...",
    "Yosuke: Yeah, that's right!",
    "Two months ago, Chisato and I...",
    "This isn't the past, but another dimension.",
    "At first, I thought it was the past too.",
    "But some things were just strange.",
    "...Until one month ago...",
    "That similar worlds exist in parallel universes...",
    "You mean that theory of multiple existing worlds...?",
    "Just when we wondered where you and Matsudaira vanished to, you were in another world?!",
    "It sounds just like a novel or a movie!",
    "And Ayase had so many plans, too~!",
    "However, if the Maki of this world...",
    "Mark: Hold on! Does that mean... Sonomura is Sonomura, but not the Sonomura from our world?!",
    "I didn't mean to deceive you, but I wasn't sure until I came back.",
    "I never imagined another world truly existed, or that I'd end up traveling there.",
    "No wonder her behavior seemed strange.",
    # 200..249 (IDs 1128..1177)
    "When I woke up, I was already in another world.",
    "Though I didn't realize it until much later.",
    "So the real Sonomura is still somewhere in the hospital, then...",
    "Maki: I'm really sorry. But...",
    "And if we defeat Kandori...",
    "Huh? Wait, Matsudaira isn't here.",
    "Yosuke: Chisato... Matsudaira-san is...",
    "Damn it!",
    "Wh-What is that?!",
    "No more of this~! What the heck is going on?!",
    "Maki: Don't tell me... That girl again?!",
    "This time, a school like this...",
    "I've erased the exits, so...",
    "no one can escape, nah-nah-na-boo-boo~!",
    "Yosuke: No doubt about it! It's that girl! She erased the exits?!",
    "It'll be a massacre! Damn it, I have to go!",
    "Please don't push yourself!",
    "Everyone, please lend a hand!",
    "Huh? This injury?",
    "When that girl came before...",
    "I'm totally pathetic, honestly!",
    "Maki: That girl must be somewhere in the school...",
    "Don't let your guard down just because she's a child. She has mysterious powers.",
    "I wonder if it really exists...",
    "Make sure you search for a way back, okay~?",
    "In other words...",
    "Yosuke Naito: Disappeared two months ago along with Chisato Matsudaira...",
    "Damn it!",
    "There shouldn't be any kids in the hallway!",
    "Kido and the others were badly hurt!",
    "D-Demons!!",
    "Elly: Are you alright?!",
    "You have nothing to worry about anymore!",
    "Hey, you okay?!",
    "What're you spacing out for?!",
    "Are you alright?!",
    "Hold it right there, demon!",
    "Demon: Oho, here they come, here they come!",
    "Let us make flowers of blood blossom to our heart's content!",
    "It's dangerous! Stay back!",
    "...Y-You! Kido?!",
    "Stay back... I'll take this one down.",
    "Demon: Hoh, a spirited brat!",
    "In honor of your spirit, first...",
    "you may rue your youthful folly in hell!",
    "Even you're a Persona user, huh~?",
    "You bastards have them too...?",
    "Nanjo: Well, that is indeed the case.",
    "By the way, it seems you...",
    "Elly: Although this place looks very similar, it is not our world.",
    # 250..299 (IDs 1178..1227)
    "Clean out your ears and listen up!",
    "This isn't the world we know!",
    "Ayase: We're the ones who want to know~! Saying this is another world...",
    "Can you even believe that?",
    "I don't get this at all~!",
    "Nanjo: We were blown here by Kandori...",
    "into a parallel world resembling ours. You are in the same situation, are you not?",
    "Or am I mistaken?",
    "Why are you here unharmed?",
    "Why are you chasing Kandori?",
    "The rest is none of your business.",
    "Maki: A child in white clothes...?",
    "We're gonna beat down Kandori and find a way back home!",
    "Come along with us!",
    "I've got no intention of grouping up with you bastards! I do whatever I want.",
    "What's with that guy...?",
    "Getting that mad just 'cause I mentioned his mother...",
    "Maki: Stop it, Inaba-kun.",
    "He has that look for a reason...",
    "Surely he has something precious...",
    "Something... precious...",
    "Brown: Prying is totally off-limits!",
    "Everyone's got things they don't want touched upon, right?",
    "Nanjo: Do you have a fever, Todoroki?",
    "That was an unusually sensible statement from you.",
    "Brown: Wh-What's that supposed to mean?!",
    "A guy as honest and open as me...",
    "ought to be registered as a living national treasure!",
    "Nanjo: A fool as always...",
    "Isn't he just unsociable~?",
    "Maki: He's... Kido-kun, right?",
    "Even Kido-kun surely must have...",
    "at least something precious to him.",
    "Like friends... or dreams for the future.",
    "Who cares, as long as everything's good right now!",
    "How should I explain it, I wonder...",
    "I'm Maki Sonomura!",
    "Nice to meet you, Kido-kun!",
    "Is there something on my face?",
    "Yeah, I totally understand.",
    "Mark: Now, now...",
    "Mark: Come on, let's get moving! ...Huh?",
    "Nanjo: Leave him be.",
    "That is fine.",
    "Nanjo: The reason Kido pursues Kandori? Well, we will learn in time.",
    "For now, it is enough if he serves our purpose.",
    "Y-You...",
    "I-I am sorry.",
    "Just like me, aren't you...?",
    "You've got secrets of your own, don't you?",
    # 300..349 (IDs 1228..1277)
    "Brown: Right? Right?",
    "That's just how people are, right?!",
    "Brown: Liar~!",
    "What's that about?!",
    "Reiji: That girl... Sonomura, was it...?",
    "Student: That guy's name is Kido-kun? He's so cool...",
    "Maki: Ah! There she is!",
    "Otherwise, I'll spank you so hard your butt will swell twice its size!",
    "Girl in Black: No way~",
    "Aki only listens to what Papa says!",
    "Mark: Calm down, Sonomura!",
    "Why you little brat~!",
    "You little punk!! I'll kill you!!",
    "Aki: Geez, shut uuup!",
    "Come out, Tesso!!",
    "Aki: Get 'em, Tesso!!",
    "Reiji: ...You bastards are gonna die.",
    "Aki: Aagh!! Dammit~!",
    "...Geez! She got away again!",
    "Nanjo: ...Just who on earth was that?",
    "Yosuke: Is everyone alright?!",
    "Yosuke: I'm really grateful to you guys.",
    "Right now, about the two worlds...",
    "I might have figured something out.",
    "I'm glad you took me seriously.",
    "What kind of guy is he, really?",
    "Yosuke: Well, that's...",
    "Alright, I'll be waiting at the Library!",
    "Elly: What was with him? Well, in any case...",
    "Brown: H-Hey! Ahh~ man, he's already gone.",
    "Is that guy seriously hurt?",
    "Mark: Then maybe you wanna stay behind alone, Ayase?",
    "Fine, I got it already~!",
    "Mark: Hey! You bastard!",
    "Don't call me by such a lame name!",
    "Maki: Stop it, you two~!",
    "Wanna go check it out? Hey, Reiji.",
    "You really are a buzzkill, aren't ya?",
    "Lighten up and let's have some fun!",
    "Don't mess with me...",
    "Mark: Well, fine by me, but...",
    "If so, he's definitely in the Library.",
    "That brat...",
    "It's news to me that he had a kid.",
    "Next time we meet, I won't let her off easy!",
    "To think someone would actually like that...",
    "The world really is full of surprises.",
    "That guy is pretty twisted, huh.",
    "Hey, you and me...",
    "And he... Naito-kun too...",
    # 350..399 (IDs 1278..1327)
    "lost someone precious to him, hasn't he...? It must be hard...",
    "...I intended to kill him from the very beginning.",
    "If that works for you, wahaha!",
    "Ooh, scary...",
    "Ayase: I wanna go home already~!",
    "Normally I'd be partying at a club right about now~!",
    "Both [Protagonist] and Inaba-kun...",
    "Ah, I'm sorry.",
    "Hey, he's actually speaking normally!",
    "Are you really a demon?",
    "Ayase: Hey, with a face like that...",
    "I'd like to meet him once.",
    "Kurokawa: Hmph. Shall we move on to the main topic?",
    "What do you think about this?",
    "Though seemingly unrelated at first glance...",
    "The same goes for this black door that suddenly appeared.",
    "And unfortunately...",
    "Nanjo: Our arrival here was inevitable. And it is we who shall expose everything...",
    "Kurokawa: Hmph, a name fitting the rumors. In fact, that today's incident would occur...",
    "Someone shut that monkey up!",
    "Mark: Hey! You bastard~!",
    "Stop it, both of you!",
    "Maki: H-Hey, Kurokawa-san...",
    "Do you mean that masked man?",
    "Kurokawa: Ah, yes...",
    "More importantly, is that alright with you?",
    "Feels kind of creepy...",
    "Nanjo: Good grief! Thanks to that idiot, I forgot what I was going to ask.",
    "His appearance is questionable, but...",
    "Something feels kinda off-kilter.",
    "Ayase: Eh~? Leaving already? You're the first person to ever drag Ayase around this much!",
    "It's a bit rowdy, but...",
    "Please find a way back somehow.",
    "If you run into Chisato,",
    "please help her. I'm begging you.",
    "This door suddenly appeared at the same time as the incident one month ago.",
    "Well, if the threads of karma guide you...",
    "It costs 2,500 yen, is that okay?",
    "What does he plan to do?!",
    "Bet 10 chips on...",
    "What on earth could it be?",
    "Nanjo: I see. Sonomura as well...",
    "Mark: Why is there always...",
    "a butterfly fluttering around?",
    "Elly: This world seems very...",
    "Brown: Meeting such a creepy...",
    "old guy...",
    "Ayase's seen it before too!",
    "Reiji: That butterfly... does it really...",
    "have nothing to do with that bastard?",
    # 400..449 (IDs 1328..1377)
    "Kurokawa totally pulled one over on us!",
    "What is it?",
    "Hey Inaba, that butterfly is...",
    "Elly: Oh, it is that butterfly!",
    "Shall I catch it and cook it up~?",
    "Brown: Nanjo, hold up!",
    "You actually interested in that sort of thing?",
    "Don't tell me your room...",
    "is full of collected butterfly specimens?!",
    "If you pull anything suspicious, I'll grab you and stomp you flat!",
    "Elly: Kandori... As expected,",
    "he is in this town as well.",
    "Ayase: Kandori's here too?!",
    "I have a super bad premonition about this!",
    "No matter how tough I am, please spare me from that woman!",
    "Saved us the trouble of looking.",
    "Mark: Said there's a demon in the underground passage...",
    "or something like that.",
    "As long as we have that, to the east side...",
    "we can cross over, so they said.",
    "That Kandori... messing with our town...",
    "I'll teach him that excessive greed is the root of ruin!",
    "I'll show him what's what!",
    "Maki: Even if you say that...",
    "somewhere...",
    "What do you think?",
    "Maki: The wall dividing this town in two was built just recently.",
    "Before that, we could freely cross over to the other side...",
    "\"Mirror of Exorcism\"... I've definitely heard that name somewhere before...",
    "Sounds like a pretty ancient name.",
    "Brown: To be honest,",
    "Even if we can't go to the east side,",
    "I wouldn't really mind~",
    "Is that so? As I thought, with that guy...",
    "Elly: Since antiquity, that mirror has possessed...",
    "\"Exorcism\"... in other words...",
    "Ayase would really appreciate it, though~",
    "...With that monster...",
    "Waaah, no way~!",
    "Reiji: Before you rely on others, you bastard...",
    "Maki: This town isn't so bad either,",
    "is it? I think paradise...",
    "is probably a place like this.",
    "It's peaceful, but every day is fun!",
    "Mark: Compared to our town, this place...",
    "It is mystical and wonderful!",
    "Let's see here, let's take a look at my face...",
    "Ayase: So this is the \"Mirror of Exorcism\"? Will it reflect Ayase's face, I wonder?",
    "Lately my skin's been totally breaking out...",
    "Maki: Found it! This is...",
    # 450..463 (IDs 1378..1391)
    "Elly: Wh-What is this...?!",
    "Ayase: Eek! What is this~?!",
    "What is this?!",
    "You mustn't take this, please...",
    "Nanjo: What was that just now...?!",
    "Mark: Like I'd know!",
    "We're screwed without this!",
    "Maki: That face just now... to Mai-chan...",
    "As long as we have this, against that monster...",
    "in the underground passage, we can fight, right?",
    "Obtained the \"Mirror of Exorcism\"!",
    "Monster: Ngggh... Aaaargh...",
    "...Yog... Sothoth...",
    "That monster looks pretty tough, doesn't it?"
]

def main():
    assert len(translations) == 464, f"Expected 464 translations, got {len(translations)}"
    with open(TARGET_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    entries = data.get("entries", [])
    assert len(entries) == 464, f"Expected 464 entries in {TARGET_FILE}, got {len(entries)}"

    for i, t in enumerate(translations):
        entries[i]["translation_en"] = t

    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    print(f"Successfully updated {len(entries)} entries in {TARGET_FILE}")

if __name__ == "__main__":
    main()
