#!/usr/bin/env python3
import json
from pathlib import Path

chunk_file = Path("scripts/retranslate2/chunks/E1_part_02.json")

translations = {
    568: "Nanjo: Neither clerk nor other customers are present.",
    569: "This place is thoroughly eerie.",
    570: "Brown: Can we eat the stuff in this store for free?",
    571: "No matter how you look at it, this convenience store is totally abandoned.",
    572: "Pinch Nurse Hizumi?",
    573: "Nurse: Go away!",
    574: "Pinch Principal Oishi?",
    575: "Yukino: What the hell is this place?!",
    576: "???: ...Oh... my.",
    577: "???: Indeed...",
    578: "Nanjo: What is this? She is wearing our school's uniform...",
    579: "Brown: Whew! Check out that cute chick!",
    580: "Ayase: Hey, you! Are you the boss of this tower?!",
    581: "???: Ufufu...",
    582: "This place is my...",
    583: "a dream solely for me.",
    584: 'Yes, I was entrusted by the Snow Queen to guard this "Tower of Hypnos".',
    585: 'I am "Kumi Hirose", and this is my dream.',
    586: "Hypnos: That is right, Kumi.",
    587: "What will you do, Kumi?",
    588: "Those guys are getting a little annoying.",
    589: "Why not kill them in one stroke,",
    590: "So, did you turn the people at school into ice?",
    591: "Kumi: ...Heh... Ufufufu...",
    592: "Can't be helped then. Why don't you all live in my dream world too?",
    593: "Hypnos: That is right, Kumi.",
    594: "But those fools will never understand.",
    595: "They cannot comprehend Kumi.",
    596: "They think Kumi is just running away.",
    597: "Come, let us show them.",
    598: "And let us teach them a lesson!",
    599: "Yukino: Wh-What the hell?!",
    600: "Boyfriend: Huh? Whoa?",
    601: "Drama Club President: Excuse me, Hirose-san!",
    602: "You haven't been showing up to drama club practice lately!",
    603: "Everyone is working as hard as they can!",
    604: "Drama Club Member: That's right, Kumi!",
    605: "After being chosen for the lead role, you can't just flake on us!",
    606: "Don't tell me you think studying is more important?",
    607: "Drama Club Member: But seriously,",
    608: "without reading lines together, we cannot put on the play!",
    609: "Drama Club Member: Yeesh~",
    610: "As expected of the number-one bookworm in class, acting all high and mighty!",
    611: "Drama Club Member: What is that supposed to mean?!",
    612: "If tests are all you care about, quit the club already!",
    613: "Drama Club President: Very well.",
    614: "If you look down on me... no, on the drama club,",
    615: "then understand your place within this group!",
    616: "If you cannot understand that, then get lost!",
    617: "Drama Club Member: Yeah! That's right!",
    618: "Just having you around makes everyone miserable!",
    619: "Drama Club Member: It's harsh, but you brought this on yourself.",
    620: "Think long and hard about it, Kumi.",
    621: "I cannot take it anymore...",
    622: "Yukino: Heh... So that was it, huh?",
    623: "Is that the reason you ran away into the dream world?",
    624: "...So? What about it?",
    625: "Kumi: Y-You...",
    626: "Didn't you feel anything seeing that?!",
    627: "You should understand my pain and sorrow immediately!",
    628: "Hypnos: Calm down, Kumi.",
    629: "Brown: Yo, yo! Kumi-chan, aren't you overthinking life a bit too much?",
    630: "Kumi-chan, you're making things way too difficult for yourself!",
    631: "Why make life so complicated?",
    632: "Take it easy and breezy, just chill out~",
    633: "Ayase: What's with you?! Playing the victim all by yourself!",
    634: "Anyway, blaming others is just totally uncool!",
    635: "Geez, I can't believe this girl!",
    636: "Kumi: But... but...!",
    637: "No matter what I did or didn't do, everyone blamed me!",
    638: "I was just trying my best in my own way!",
    639: "Hypnos: Indeed! You did nothing wrong, Kumi!",
    640: 'Nanjo: ..."Other people"... is that it?',
    641: "Hmph. Truly a cowardly way of living.",
    642: "And fleeing from the very burden of living...",
    643: "In the end, you merely refuse to face reality.",
    644: 'Elly: "Other people", is it?',
    645: "Kumi: Wh-Who do you think you are?! All of you!",
    646: "Hypnos: Enough!",
    647: "It's all right now, Kumi.",
    648: "Let us destroy these intruders!",
    649: "Yukino: Quit trying to act tough.",
    650: "Then defeating the Hypnos here will wake everyone up, right?",
    651: "You guys must be projections from somewhere in this tower.",
    652: 'The dream created by "Kumi Hirose"...',
    653: "In other words, if we defeat you, the dream ends!",
    654: "Yukino: That Kumi girl is hiding on the top floor, isn't she?",
    655: "Ayase: What a totally annoying chick, honestly!",
    656: "Nanjo: What is with that woman?! Self-absorbed to the core!",
    657: "Brown: But y'know, I kinda get where she's coming from...",
    658: "Elly: Kumi-san's loneliness must have been overwhelming...",
    659: "Kumi: Wh-What is it?!",
    660: "I-If you lay a hand on me, Hypnos will destroy you!",
    661: "Pinch Kumi?",
    662: "Kumi: Wh-What a terrible judge of character you are!",
    663: "Tadashi: ...It's all right, Tamaki-chan. I'm right here.",
    664: "Tadashi: See? I told you so!",
    665: "Tamaki: We were always fighting, but...",
    666: "Tamaki: If I leave you alone, you always get into trouble!",
    667: "Tamaki: But thanks to that dream,",
    668: "I feel like I can finally be honest with myself...",
    669: "Tamaki: I love you, Tadashi!",
    670: "Yukino: Look at them go, all lovey-dovey.",
    671: "Well, at least all three are safe and sound.",
    672: "Are you feeling all right physically?",
    673: "Tadashi: Ah! Ahhh! Not you guys again!",
    674: "Tadashi: Don't interrupt us!",
    675: "Tadashi: Right, Tamaki-chan?",
    676: "Tamaki: ...Mayuzumi-san, thank you for waking us up.",
    677: "Nanjo: Truly a colossal waste of time. Wasted rescue effort.",
    678: "Nanjo: That is what this amounted to.",
    679: "Brown: What the heck?! That's so cold, Tamaki-chan!",
    680: "Brown: Treating us so coldly after all we did!",
    681: "Brown: We worked our butts off to rescue you two!",
    682: "Don't you remember anything at all?",
    683: "Brown: The great me is super heartbroken!",
    684: "Tadashi: What do you mean remember...? We were just having a sweet dream!",
    685: "Tadashi: ...Huh??",
    686: "Tadashi: When I woke up, Tamaki-chan was right in front of me,",
    687: "Tadashi: and she was gazing at me with such loving eyes!",
    688: "Yukino: All right, all right, we get it!!",
    689: "Yukino: We understand completely!",
    690: "Just tell us one thing, will ya?",
    691: "After that, we won't get in the way",
    692: "of you two lovebirds anymore.",
    693: "Nanjo: So then,",
    694: 'do either of you happen to have a "Mirror Shard"?',
    695: "Nanjo: Indeed, I did not expect much from the start, but...",
    696: "Elly: To save the school, it is an item we desperately need.",
    697: "Elly: Does anything come to mind?",
    698: "Tamaki-chan: ...Geez! Tadashi, be serious!",
    699: 'Tamaki: A "Mirror Shard"... could it be this?',
    700: "Tadashi: Th-That you had something like that...",
    701: "Tadashi: I never heard you had that on you...!",
    702: "Tadashi: Even though we pledged our love to each other!",
    703: "Tadashi: Keeping secrets is so mean!",
    704: "Tamaki-chan: ...Hold on! I only just found it in my pocket!",
    705: "Tamaki: Here, if this helps, please take it.",
    706: "Tamaki: Sorry that this is all I can do to help...",
    707: "Tamaki: Honestly, Tadashi and I wish we could come along, but...",
    740: "Elly: We would only end up being dead weight, it seems.",
    741: "Tadashi: Ah! Ahhh! Take care, you guys!",
    742: "Tadashi-kun: Your business is done, right? Leave us alone now!",
    743: "Tadashi: Please give us some privacy, I beg of you.",
    744: "Tamaki-chan: Are you trying to get between me and Tadashi?",
    745: "Tamaki-chan: Sorry, I can only think about Tadashi right now.",
    746: "Tamaki: I really cannot focus on anything else.",
    747: "Ayase: How is it...? Sensei?",
    748: "Ayase: Does it hurt...?",
    749: "Nurse: Ughhh!! My head is pounding...",
    750: "Nurse: I was just at the best part of my dream, too...",
    751: "Yukino: Let's turn this school back to normal without ice!",
    752: "Yukino: Finally awake, huh, teachers?!",
    753: "Yukino: How are you feeling? Any injuries?",
    754: "Vice Principal Sori: What on earth is the meaning of this?!",
    755: "Vice Principal Sori: Where in the world is this place?!",
    756: "Vice Principal Sori: Is this your doing, you delinquents?!",
    757: "Vice Principal Sori: You good-for-nothing brats!",
    758: "Vice Principal Sori: Principal, say something to these troublemakers!",
    759: "Principal Oishi: Have you calmed down? Are you unharmed?",
    760: "Principal Oishi: ...Mayuzumi-san, everyone, thank you.",
    761: "Principal Oishi: If no one is hurt, that is good.",
    762: "Yukino: More importantly, teachers, do you have a Mirror Shard?",
    763: "Brown: Calling us delinquents is so cruel, Vice Principal!",
    764: "Brown: We went through hell and back to save you guys!",
    765: "Brown: A little word of thanks...",
    766: "Brown: ...would be nice for the great me and my team!",
    767: "Brown: Ah, whatever! Forget it!",
    768: "Brown: Hey, do you guys know about the Mirror Shard?",
    769: "Vice Principal Sori: Ah, you mean this thing?",
    770: "Vice Principal Sori: My suit pocket tore because of this jagged thing!",
    771: "Vice Principal Sori: Well,",
    772: "Vice Principal Sori: none of that matters right now.",
    773: "Vice Principal Sori: Who cares about that anyway?!",
    774: "Vice Principal Sori: By the way! What are you brats planning to do with this?!",
    775: "Vice Principal Sori: No! Giving this to you will only make things worse!",
    776: "Ayase: What did you say?! You bald Hannya!!",
    777: "Ayase: That's why unlike Principal Oishi, everyone hates you!",
    778: "Ayase: Hand over the shard already!",
    779: "Principal Oishi: Now, now, calm down everyone.",
    780: "Principal Oishi: Ayase-san, a lady must not use such harsh words.",
    781: "Principal Oishi: First, try looking at things from the students' perspective.",
    782: "Principal Oishi: Please give them the Mirror Shard.",
    783: 'Obtained the "Mirror Shard".',
    784: "Nanjo: Hmph. You should have handed it over obediently from the start.",
    785: "Nanjo: The only ones walking the truly righteous path in this school are ourselves.",
    786: "Elly: This is an indispensable treasure for us,",
    787: "Elly: and furthermore, essential to saving the school.",
    788: "Principal Oishi: For now, I shall not ask your reasons.",
    789: "Principal Oishi: But please, do not do anything reckless.",
    790: "Principal Oishi: Go on ahead, students.",
    791: "Vice Principal Sori: Hmph! I won't stop you anymore. Go!",
    792: "Vice Principal Sori: ...Hey, you brats!",
    793: "Vice Principal Sori: If... if the school returns to normal...",
    794: "Vice Principal Sori: assemble in the Principal's office immediately!",
    795: "Vice Principal Sori: You will give me a full lecture and explanation!",
    796: "Vice Principal Sori: Come! All of you, be prepared!",
    797: "Yukino: Geez, what a stubborn old man.",
    798: "Yukino: Leave it to us! We'll save the school for sure!",
    799: "Yukino: We'll definitely protect everyone!",
    800: 'Yukino: "Without fail", you can count on it!',
    801: "Yukino: There's nothing left to do in this room, is there?",
    802: "Yukino: We should hurry on ahead.",
    803: "Yukino: We gotta move fast.",
    804: "Ayase: Vice Principal will totally look at us in a new light now!",
    805: "Nanjo: At any rate, it is best that our teachers are unharmed.",
    806: "Brown: All right! Hannya owes the great me a huge favor now!",
    807: "Brown: Now Vice Principal Hannya can't act all bossy around us!",
    808: "Brown: Kekeke! No more strutting around like he owns the place!",
    809: "Brown: ...Though saying that to his face is kinda terrifying!",
    810: "Brown: He really is scary, that Vice Principal!",
    811: "Elly: In any case, that the teachers are safe is a relief.",
    812: "Vice Principal Sori: Yeah... What a strange dream that was...",
    813: "Vice Principal Sori: Even so, it was a good dream...",
    814: "Vice Principal Sori: Ahh, just a little more and I could remember it!",
    815: "Principal Oishi: Even so, it was quite an unpleasant nightmare.",
    816: "Yukino: Whoa?! What is this room?!",
    817: "Yukino: Outer space?! What kind of room is this?!",
    818: "Kumi: Nice to meet you, everyone.",
    819: "Kumi: Entrusted by the Snow Queen to guard this tower,",
    820: "Kumi: my name is Kumi.",
    821: "Kumi: I was ordered to kill all of you, but...",
    822: "Kumi: why not quietly surrender and live happily with us in dreams?",
    823: "Kumi: Wouldn't that be wonderful?",
    824: 'Nanjo: "I am Kumi Hirose"? A young girl guarding this tower?!',
    825: "Nanjo: Do not make me laugh with such absurd jokes!",
    826: "Nanjo: You wear our school uniform. What are you doing here?!",
    827: "Brown: A cute girl like you is the boss here?! Give me a break!",
    828: "Ayase: A gloomy, weak-looking nerd like you can't be the boss!",
    829: "Ayase: You're totally weak, no way you're the guardian!",
    830: "Kumi: I'm going to kill you right now... you fools.",
    831: "Kumi: That's enough. Disappear from before my eyes!",
    832: "Nanjo: What?! This murderous intent!!",
    833: "Elly: What an ominous, sinister aura...!",
    834: "Yukino: P-Persona?! She's summoning a monster!!",
    835: "Yukino: No holding back, everyone! Let's go!!",
    836: "Yukino: ...Hmph! Looks like this is the top floor!",
    837: 'Yukino: End of the line, "Kumi Hirose"!',
    838: "Yukino: Prepare yourself, Kumi!",
    839: "Kumi: You have finally arrived... trapped in dull reality.",
    840: "Kumi: Refusing to believe in the paradise of dreams.",
    841: "Nanjo: Which of us is the fool...?! Fleeing from reality itself!",
    842: "Brown: Kumi-chan... Fighting a cute girl breaks my heart!",
    843: "Brown: But for justice and the school, take this beatdown!",
    844: "Ayase: Heh-heh! Five against one, you don't stand a chance!",
    845: "Kumi: Judging others purely by appearances... You fools!",
    846: "Nanjo: What is that?! Was Hypnos not a product of her dream?!",
    847: "Elly: Could it be?! Hypnos was controlling Kumi-san's dream!",
    872: "Kumi: If only friends like you had been by my side...",
    873: "Kumi: ...Goodbye, everyone.",
    874: "Obtained 1 Mirror Shard.",
    875: 'Yukino: "Kumi Hirose"... She was just another victim of the mask.',
    876: "Yukino: Let's head back! We have to save Saeko-sensei!",
    877: "Yukino: Hurry, before it's too late!",
    878: "Tower of Hypnos conquered!",
    879: "Brown: Kumi-chan... May you find peace.",
    880: "Yukino: Feels like an ominous presence is watching us...",
    881: "Michiko: Good day, ladies and gentlemen. Welcome to this tower.",
    882: "Michiko: I welcome you from the bottom of my heart.",
    883: "Nanjo: Borrowing the Snow Queen's authority, you petty fox!",
    884: "Nanjo: You are nothing more than a small fry!",
    885: "Elly: Are you the Guardian of this tower?",
    886: "Ayase: That's right! Too scared of Ayase to show your face!",
    887: "Ayase: The boss here sounds totally weak and pathetic!",
    888: "Michiko: My, my, what delightfully insolent little brats!",
    889: "Michiko: Weak fools shatter so quickly when tormented!",
    890: "Michiko: You'll make such delightful playthings!",
    891: "Michiko: I won't have to hold back in the slightest!",
    892: "Michiko: Weak opponents break so fast when bullied!",
    893: "Michiko: It's almost boring how fast they crumble!",
    894: 'Michiko: I am "Michiko Matsudaira", guardian of Nemesis!',
    895: "Michiko: You there!! Wouldn't you rather be my pet?",
    896: "Michiko: Rather than dying with these wretches!",
    897: "Nanjo: You mean ME?! Become a pet to a woman with an attitude like yours?!",
    898: "Nanjo: And to someone as hideous in personality as you?!",
    899: "Nanjo: Don't you dare insult me, you wretched woman!",
    900: "Nanjo: I, Kei Nanjo, will make you regret uttering such words!",
    901: "Nanjo: You shall regret this in the depths of hell!",
    902: 'Brown: You mean the great me?? Make "Brown-sama" your pet?!',
    903: "Brown: Making fun of me like that! I'll give your ugly face some surgery!",
    904: "Brown: I'll beat that ugly mug of yours into next week!",
    905: "Michiko: And here I offered you mercy, you insolent rabble!",
    906: "Michiko: Very well, little brats... I shall break you with my own hands!",
    907: "Michiko: Not a single one of you will leave here in one piece!",
    908: "Michiko: I have lifted the time limit on this tower!",
    909: "Michiko: Take as long as you like, I eagerly await your arrival! Farewell!",
    910: "Yukino: Michiko Matsudaira... There's definitely a catch to lifting the time limit.",
    911: "Yukino: No time limit? Smells fishy to me.",
    912: "Ayase: That Michiko chick reminds me of someone all stuck-up and high-and-mighty!",
    913: "Ayase: Michiko acts like she's the queen of the universe!",
    914: "Ayase: Super haughty and arrogant!",
    915: 'Brown: She\'s the spitting image of a certain someone whose name starts with "Na"!',
    916: "Brown: Between you and me, she acts just like Nanjo!",
    917: "Elly: No time limit? We should remain very cautious.",
    918: "Elly: There is unquestionably some hidden trap behind this.",
    919: "Elly: We had better not let our guard down regarding the time limit.",
    920: "Demon Teacher: Hey! Who said you could spill that milk, de-gowasu?!",
    921: "Demon Teacher: Milk is good for you! Drink it all, little piggy!",
    922: "Demon Teacher: And you over there, four-eyes! Drop your chest to the floor on those push-ups!",
    923: "Demon Teacher: Or I'll double your quota, de-gowasu!",
    924: "Toro: S-Save meee!!",
    925: "Toro: Forgive meee!!",
    926: "Toro: I just...",
    927: "Toro: anything but this!",
    928: "Toro: Dairy products are my absolute nightmare!!",
    929: "Toro: I can't take another drop!!",
    930: "Kurokawa: As I thought...",
    931: "Kurokawa: I can't do push-ups~",
    932: "Kurokawa: Someone meant for brain work like me...",
    933: "Kurokawa: was never built for physical labor!",
    934: "Kurokawa: My arms are turning into jelly!",
    935: "Kurokawa: My body wasn't made for this!",
    936: "Kurokawa: *wheeeeze*",
    937: "Yukino: Weren't you two supposed to be back at school?!",
    938: "Toro: Noooo!",
    939: "Toro: Stop it pleaseee!!",
    940: "Toro: I'm gonna die...!",
    941: "Demon Teacher: Drink more, little piglet, de-gowasu!",
    942: "Demon Teacher: Become a milk-drinking machine, de-gowasu!",
    943: "Toro: I can't drink any moreee...",
    944: "Kurokawa: Ahahaha... I see fairies...",
    945: "Kurokawa: Mommy, is that you...?",
    946: "Demon Teacher: Hey! Don't break before Lady Michiko gets to break you, de-gowasu!",
    947: "Nanjo: Torture purely calculated around their specific weaknesses...",
    948: "Nanjo: Truly sadistic and terrifying.",
    949: "Toro: Bleeeaaargh!!",
    950: "Toro: Huh?",
    951: "Toro: A-A-Ayase-san! Everyone!",
    952: "Toro: S-S-Save meee!",
    953: "Michiko: That is because they are ugly! Ugliness is a sin!",
    954: "Michiko: And I, the beautiful Michiko, am passing judgment on them!",
    955: "Michiko: Punishing their hideous existence!",
    956: "Nanjo: Sorry to disappoint, but ugly or not, they are our schoolmates.",
    957: "Nanjo: We cannot overlook this cruelty. Release them!",
    958: "Yukino: Unlock those chains and stop this torture right now!",
    959: "Brown: What did you say?! You ugly hag, pick on someone your own size!",
    960: "Michiko: My, my! What touching friendship! How delightful!",
    961: "Michiko: If you wish to save your friends,",
    962: "Michiko: race up to my chamber on the top floor before they expire! Ohohoho!",
    963: "Michiko: The key is waiting in a grand treasure chest!",
    964: "Michiko: My room is just at the top floor... Farewell!",
    965: 'Michiko: The "Mirror Shard" is also in a large treasure chest~',
    966: "Michiko: If you can make it in time, that is!",
    967: "Michiko: Farewell, little heroes!",
    968: "Toro: P-Please save me! Ayase-san!",
    969: "Toro: My heart belongs only to you!",
    970: "Toro: The key to my heart is yours!",
    971: "Demon Teacher: Come on, keep drinking and pushing, de-gowasu!",
    972: "Yukino: We can't leave them like this! We gotta find that key fast!",
    973: "Yukino: Michiko... She's utterly vile.",
    974: "Ayase: Toro and Kurokawa are pathetic, but Michiko is way worse!",
    975: "Nanjo: Rather than the Mirror Shard, saving our schoolmates comes first.",
    976: "Brown: They're annoying dorks, but they're our classmates! Let's save 'em!",
    977: "Elly: That Michiko... Her cruelty knows no bounds.",
    978: "Toro: No more milk... I'm gonna burst...",
    979: "Yukino: What the hell?! Is this chest empty?!",
    980: "Nanjo: Knowing that Michiko, she filled the tower with fake chests.",
    981: "Nanjo: We must hurry back to the torture room.",
    982: "Elly: Is this what Michiko meant by lifting the time limit?",
    983: "Elly: It was a trap to make us waste precious time!",
    984: "Ayase: Ugh, I'm gonna die! Running up and down these stairs!",
    985: "Ayase: If the key isn't in this chest, Ayase's gonna explode!",
    986: "Ayase: All this running around is totally exhausting!",
    987: "Nanjo: But this chest looks distinctly different from the fakes.",
    1028: "Ayase: Acting all high and mighty is just unbearable!",
    1029: "Ayase: In the end, arrogant rich girls are the worst!",
    1030: "Michiko: To think lowborn rabble like you reached my chamber!",
    1031: 'Nanjo: "Ohoho," how noisy. Cease your arrogant cackling!',
    1032: "Nanjo: Ayase is correct. Your vanity is repulsive.",
    1033: "Michiko: How dare you insult my beauty!!",
    1034: "Michiko: Beauty is absolute in this world!",
    1035: "Yukino: Acting like a queen when you're just a puppet of the mask!",
    1036: "Michiko: This face was given to me by the Snow Queen!",
    1037: "Michiko: And your ugly faces will be wiped out!",
    1038: "Nanjo: What did you say?!",
    1039: "Brown: Hey, shut your trap, you conceited witch!",
    1040: "The tower trembles with demonic power!",
    1041: "Nanjo: Indeed, her power is astonishing!",
    1042: "Elly: Michiko is being consumed by Nemesis!",
    1043: "Michiko: Now then... fall into eternal despair!",
    1044: "Michiko: Savor your regrets in death!",
    1045: "Michiko: Taste my vengeance!",
    1046: "Michiko: Suffer more, you ugly worms!!",
    1047: "Michiko: Your screams are music to my ears!",
    1048: "Yukino: Is that your Persona, or the monster within you?!",
    1049: "Yukino: We have no choice but to take her down!",
    1050: "Yukino: Looks like this is the end of the line for you, Michiko!",
    1051: "Michiko: How could I lose so easily to these peasants?!",
    1052: "Michiko: Even after all my brilliant traps!",
    1053: "Michiko: To defeat ME, the magnificent Michiko Matsudaira!",
    1054: "Michiko: You filthy brats!",
    1055: "Michiko: I will make you pay for this humiliation!",
    1056: "Nanjo: What did you say?!",
    1057: "Michiko: If only friends had reached out to me back then...",
    1058: "Michiko: I absorbed so much power from the tower!",
    1059: "Michiko: All thanks to you taking your sweet time getting here!",
    1060: "Nanjo: Indeed, her power has swelled dramatically!",
    1061: "Michiko: Now, perish under Nemesis' wrath!",
    1062: "Yukino: Hmph! Take this!!",
    1063: "Michiko: I... I lost...?!",
    1064: "Michiko: How could I be defeated...?!",
    1065: "Michiko: By mere humans like them...",
    1066: "Nanjo: What an obnoxious woman.",
    1067: "Nanjo: That you lost and we prevailed is an undeniable reality.",
    1068: "Nanjo: Face the reality of your defeat.",
    1069: "Michiko: No... disappear... Leave me alone!",
    1070: "Michiko: Back then, without reason, everyone called me ugly and ridiculed me...",
    1071: "Michiko: Mocking a frail, defenseless girl...",
    1072: "Michiko: The only one who was gentle to me was the Snow Queen!",
    1073: "Nanjo: That is... while your pain may be real, hurting others to soothe your grudge is inexcusable.",
    1074: "Elly: Michiko-san, true beauty comes from within the heart.",
    1075: "Elly: Lashing out at the world will never heal your scars.",
    1076: "Michiko: Without this mask and power, I am nothing...",
    1077: "Michiko: Are you still mocking me?!",
    1078: "Michiko: Farewell, you wretches!!",
    1079: "Michiko: When the curse is broken, I shall fade away!",
    1080: "Michiko: I leave the Mirror Shard with you...",
    1081: "Obtained 2 Mirror Shards.",
    1082: 'Yukino: "Michiko Matsudaira"... What a tragic girl.',
    1083: "Yukino: I hope we never have to fight a classmate like that again.",
    1084: "Yukino: In the end, the real treasure was saving our friends.",
    1085: "Yukino: Let's head back!",
    1086: "Tower of Nemesis conquered!",
    1087: "Upon entering the tower, the trial begins.",
    1088: "Yukino: What the...?! A voice from out of nowhere?!",
    1089: "???: Yahoo~! Welcome to Thanatos Tower!",
    1090: 'Yuriko: It\'s your lovely host, "Yuriko Yamamoto"-chan!',
    1091: "Nanjo: What manner of foolish joke is this?!",
    1092: "Nanjo: Show yourself if you are the guardian!",
    1093: "Yuriko: Call me Yuriko-chan~!",
    1094: "Nanjo: ...Preposterous.",
    1095: "Brown: Hey! What's your deal, talking like some wacky TV host?!",
    1096: "Ayase: Her way of talking is super weird, like totally bizarre!",
    1097: "Ayase: Like, you're crazy weird, honestly!",
    1098: "Ayase: Right?! Totally nuts!",
    1099: "Yukino: Who are you?! Show yourself!",
    1100: "Nanjo: Do you intend to challenge us right here?!",
    1101: "Nanjo: Do you wish to cross blades with us?!",
    1102: "Yuriko: Don't say such scary things, no no no~!",
    1103: "Yuriko: Listen carefully to the rules of this tower!",
    1104: "Yuriko: Just kidding! Tee-hee!",
    1105: "Yuriko: Do your best to solve the candle puzzle and reach me!",
    1106: "Yukino: She's definitely up to no good.",
    1107: "Yukino: Something about her gives me the creeps.",
    1108: "Yukino: Damn it! Another trap?!",
    1109: "Ayase: What is with this girl?! Totally conniving!",
    1110: "Ayase: That sneaky little brat!",
    1111: "Ayase: She totally treats life like a silly game!",
    1112: "Nanjo: Good grief... A guardian who relies entirely on deceit and trickery.",
    1113: "Brown: Hey, hey! We gotta be careful with these candles!",
    1114: "Elly: That Yuriko... She thrives on misleading us with traps.",
    1115: "Elly: Turning our own choices into traps!",
    1116: "Yukino: Ugh?! The door won't budge!",
    1117: "Yukino: Is this the right one?",
    1118: "Yukino: Which candle flame should we put out?",
    1119: "Yukino: Extinguish it!",
    1120: "Yuriko: Yay, yaaay~! You fell right into my trap!",
    1121: "Yuriko: As promised, I'll take your Persona!",
    1122: "Yuriko: Persona taken away~!",
    1123: "Yukino: Damn it all! She sealed our Persona!!",
    1124: "Will you extinguish the candle flame?",
    1125: "Extinguish this candle flame?",
    1126: "The candle is unlit.",
    1127: "The candle is burning.",
    1128: "Extinguish the flame of either candle?",
    1129: "The door now opens freely.",
    1130: "Will you open the door?",
    1131: "Yuriko: Oh, were you fooled again? Too bad~!",
    1132: "Yukino: That is so blatantly suspicious!",
    1133: "Yukino: It's definitely another trap, without a doubt!",
    1134: "Yuriko: Aww, that's so mean! So mean!",
    1135: "Yuriko: After Yuriko prepared such a nice hint for you!",
}

with open(chunk_file, "r", encoding="utf-8") as f:
    chunk_data = json.load(f)

entries = chunk_data.get("entries", [])
missing = []
for e in entries:
    eid = e["id"]
    if eid in translations:
        e["translation_en"] = translations[eid]
    else:
        missing.append((eid, e.get("text_jp", "")))

if missing:
    print(f"[!] Warning: Missing {len(missing)} translations!")
    for m in missing[:20]:
        print(f"   Missing ID {m[0]}: {repr(m[1])}")
else:
    print(f"[+] All {len(entries)} entries successfully translated!")

with open(chunk_file, "w", encoding="utf-8") as f:
    json.dump(chunk_data, f, ensure_ascii=False, indent=1)

print(f"[+] Successfully wrote {chunk_file}")
